// questions.js - Repositori Data Ujian & Soal (Multi-Mapel)
const QUIZ_DATA = [
  {
    id: "PKN",
    title: "Pendidikan Kewarganegaraan",
    classDefault: "Kelas 6 (Aqaba)",
    duration: 90,
    theme: "from-red-500 to-orange-500",
    secure: "8813",
    questions: [
      {
        q: "Anak memiliki hak di rumah, salah satu hak anak di rumah adalah …",
        options: [
          "Membersihkan rumah setiap hari",
          "Mendapat kasih sayang dari orang tua",
          "Membantu pekerjaan orang tua",
          "Menjaga kebersihan kamar",
        ],
        answer: "B",
      },
      {
        q: "Kewajiban yang sebaiknya dilakukan sebagai anak di rumah adalah ...",
        options: [
          "Membantu orang tua",
          "Mendapat hadiah",
          "Bermain sepanjang hari",
          "Mendapatkan tempat tinggal",
        ],
        answer: "A",
      },
      {
        q: "Penetapan pembentukan BPUPKI disampaikan oleh Kumakici Harada pada tanggal ..",
        options: [
          "29 Mei 1945",
          "5 Maret 1945",
          "1 Maret 1945",
          "29 Maret 1945",
        ],
        answer: "C",
      },
      {
        q: "Perhatikan gambar tarian tradisional berikut!\nTarian tersebut berasal dari daerah...",
        options: ["Sumatera Barat", "Bali", "Jawa Tengah", "Kalimantan Timur"],
        answer: "B",
        img: "PKN-4.webp",
      },
      {
        q: "Perhatikan gambar berikut ini !\nSenjata tradisional di atas berasal dari daerah …",
        options: ["Jawa Tengah", "Jawa Barat", "Jawa Timur", "Bali"],
        answer: "B",
        img: "PKN-5.webp",
      },
      {
        q: "Perhatikan gambar berikut ini !\nAlat musik tradisional Tifa berasal dari daerah …",
        options: ["Papua", "Bali", "Sulawesi", "Aceh"],
        answer: "A",
        img: "PKN-6.webp",
      },
      {
        q: "Perhatikan pernyataan berikut!\nDalam sidang BPUPKI, terdapat peristiwa penting yang menjadi awal lahirnya dasar negara Indonesia. Pada saat itu, Ir. Soekarno menyampaikan gagasan tentang dasar negara yang kemudian dikenal sebagai Pancasila.\nPeristiwa yang menandai kelahiran Pancasila adalah ....",
        options: [
          "Pembacaan teks Proklamasi",
          "Sidang pertama BPUPKI pada 29 Mei 1945",
          "Pidato Ir. Soekarno pada 1 Juni 1945",
          "Pengesahan UUD 1945",
        ],
        answer: "C",
      },
      {
        q: "Perhatikan pernyataan berikut!\nSumpah Pemuda merupakan peristiwa penting dalam sejarah Indonesia yang menunjukkan persatuan para pemuda dari berbagai daerah.\nPeristiwa ini menjadi tonggak awal semangat persatuan bangsa Indonesia.\nKapan peristiwa Sumpah Pemuda terjadi?",
        options: [
          "17 Agustus 1945",
          "20 Mei 1908",
          "28 Oktober 1928",
          "1 Juni 1945",
        ],
        answer: "C",
      },
      {
        q: "Pada tanggal berapakah Ir. Soekarno menyampaikan usulan rumusan dasar negara dalam sidang BPUPKI?",
        options: [
          "1 Juni 1945",
          "29 Mei 1945",
          "31 Mei 1945",
          "17 Agustus 1945",
        ],
        answer: "A",
      },
      {
        q: "Perhatikan daftar tokoh berikut!\n1. Mr. Mohammad Yamin\n2. Drs. Mohammad Hatta\n3. Prof. Dr. Soepomo\n4. Ir. Soekarno\nManakah tokoh yang menyampaikan usulan dasar negara pada sidang BPUPKI tanggal 29 Mei 1945?",
        options: [
          "Tokoh Nomor 4",
          "Tokoh Nomor 2",
          "Tokoh Nomor 3",
          "Tokoh Nomor 1",
        ],
        answer: "D",
      },
      {
        q: "Perhatikan beberapa pasal dalam UUD 1945 berikut:\nPasal 27 ayat (1) -> Segala warga negara bersamaan kedudukannya di dalam hukum dan pemerintahan dan wajib menjunjung hukum dan pemerintahan itu dengan tidak ada kecualinya.\nPasal 28A -> Setiap orang berhak untuk hidup serta berhak mempertahankan hidup dan kehidupannya.\nPasal 28C ayat (1) -> Setiap orang berhak mengembangkan diri melalui pemenuhan kebutuhan dasarnya.\nPasal 31 ayat (1) -> Setiap warga negara berhak mendapat pendidikan.\nBerdasarkan pasal-pasal tersebut, yang menunjukkan hak perlakuan yang sama di hadapan hukum adalah ....",
        options: [
          "Pasal 28A",
          "Pasal 31 ayat (1)",
          "Pasal 27 ayat (1)",
          "Pasal 28C ayat (1)",
        ],
        answer: "C",
      },
      {
        q: "Nilai yang terkandung dalam gambar diatas sesuai dengan sila pertama Pancasila yaitu....",
        options: [
          "Menghargai pendapat orang lain",
          "Melaksanakan ibadah sesuai kepercayaan masing-masing",
          "Mengutamakan kepentingan bersama",
          "Menjaga persatuan dan kesatuan bangsa",
        ],
        answer: "B",
        img: "PKN-12.webp",
      },
      {
        q: "Perhatikan gambar perumus Pancasila berikut.\nBerdasarkan gambar di atas, perumus Pancasila nomor 1 dan 4 adalah …",
        options: [
          "Ir. Soekarno & Wahid Hasyim",
          "Ir. Soekaro & Muhammad Hatta",
          "Muhammad Hatta & Wahid Hasyim",
          "Wahid Hasyim & Ir. Soekarno",
        ],
        answer: "A",
        img: "PKN-13.webp",
      },
      {
        q: "Perhatikan pernyataan berikut ini.\n1) Menghormati guru\n2) Menjalankan ibadah\n3) Jujur saat ujian\n4) Berdoa sebelum makan\nDari pernyataan di atas, yang termasuk norma agama adalah nomor …",
        options: ["1 dan 2", "2 dan 3", "2 dan 4", "1 dan 4"],
        answer: "C",
      },
      {
        q: 'Perhatikan pernyataan di bawah ini!\n"Sebelum berangkat ke sekolah, Bayu selalu membiasakan diri untuk berpamitan dan mencium tangan kedua orang tuanya sebagai bentuk penghormatan."\nBerdasarkan pernyataan tersebut, tindakan yang dilakukan oleh Bayu merupakan bentuk penerapan dari…',
        options: [
          "Norma Hukum",
          "Norma Agama",
          "Norma Kesopanan",
          "Norma Kesusilaan",
        ],
        answer: "C",
      },
      {
        q: "Perhatikan pernyataan berikut:\n'Setiap pemeluk agama wajib menjalankan ibadah dan menjauhi larangan-Nya sesuai dengan petunjuk yang terdapat dalam kitab suci masing-masing.'\nBerdasarkan pernyataan tersebut, sumber utama dari norma agama adalah…",
        options: [
          "Bisikan hati nurani manusia tentang baik dan buruk",
          "Peraturan yang dibuat oleh lembaga negara",
          "Hasil kesepakatan tokoh adat di suatu daerah",
          "Wahyu Tuhan Yang Maha Esa yang tertuang dalam kitab suci",
        ],
        answer: "D",
      },
      {
        q: "Di sekolah, setiap siswa memiliki hak dan kewajiban.\nHak adalah sesuatu yang seharusnya diterima oleh siswa, sedangkan kewajiban adalah sesuatu yang harus dilakukan dengan penuh tanggung jawab.\nManakah yang merupakan contoh hak siswa di sekolah?",
        options: [
          "Mengerjakan tugas yang diberikan guru tepat waktu",
          "Mematuhi tata tertib sekolah",
          "Mendapatkan pelajaran dan bimbingan dari guru",
          "Menjaga kebersihan lingkungan sekolah",
        ],
        answer: "C",
      },
      {
        q: "Di lingkungan sekolah, setiap siswa memiliki peran penting dalam menciptakan suasana belajar yang nyaman.\nOleh karena itu, siswa harus melaksanakan kewajibannya dengan penuh tanggung jawab.\nManakah yang merupakan contoh kewajiban siswa di sekolah?",
        options: [
          "Mendapatkan nilai yang baik dari guru",
          "Menggunakan fasilitas sekolah dengan bebas",
          "Mendapatkan perlindungan dari pihak sekolah",
          "Mematuhi tata tertib yang berlaku di sekolah",
        ],
        answer: "D",
      },
      {
        q: "Apa manfaat utama dari melakukan musyawarah dalam mengambil keputusan untuk kepentingan bersama?",
        options: [
          "Mencari siapa yang paling hebat dalam berdebat",
          "Menghasilkan keputusan yang adil dan disepakati bersama",
          "Mempercepat waktu tanpa perlu berdiskusi",
          "Memastikan pendapat pemimpin selalu diikuti",
        ],
        answer: "B",
      },
      {
        q: "Nayya mengunjungi salah satu provinsi di Indonesia. Dia melihat bangunan seperti gambar di atas. Bangunan tersebut merupakan ikon dari ….",
        options: [
          "Provinsi Jawa Barat",
          "Nusa Tenggara Barat",
          "Provinsi Sumatra",
          "Provinsi Papua",
        ],
        answer: "D",
        img: "PKN-20.webp",
      },
      {
        q: "Perhatikan pernyataan berikut:\nProvinsi Nanggroe Aceh Darussalam (NAD) memiliki kewenangan khusus dalam menjalankan kehidupan masyarakatnya, termasuk dalam bidang hukum dan budaya yang berbeda dengan provinsi lain di Indonesia.\nBerdasarkan pernyataan tersebut, keistimewaan Provinsi NAD adalah ....",
        options: [
          "Memiliki ibu kota negara",
          "Menerapkan hukum adat secara bebas tanpa aturan",
          "Diberi kewenangan untuk menerapkan syariat Islam",
          "Menjadi pusat perdagangan internasional utama",
        ],
        answer: "C",
      },
      {
        q: "Perhatikan pernyataan berikut:\nGotong royong merupakan sikap bekerja sama untuk mencapai tujuan bersama tanpa mengharapkan imbalan.\nBerdasarkan pernyataan tersebut, contoh kegiatan gotong royong di sekolah adalah ....",
        options: [
          "Mengerjakan tugas sendiri tanpa bantuan teman",
          "Membersihkan kelas bersama-sama setelah kegiatan belajar",
          "Mencontek pekerjaan teman saat ulangan",
          "Bermain sendiri saat jam istirahat",
        ],
        answer: "B",
      },
      {
        q: "Nama suku bangsa asal Provinsi Jawa Barat adalah suku sunda, dan terdapat suku lain di daerah lainnya.\nSikap yang harus kita tunjukkan terhadap keberagaman suku bangsa di Indonesia adalah….",
        options: [
          "Saling mengejek antar suku",
          "Saling menghargai antar perbedaan suku",
          "Tidak menghargai suku lain",
          "Merasa lebih baik dari suku daerah yang lain",
        ],
        answer: "B",
        img: "PKN-23.webp",
      },
      {
        q: "Berdasarkan gambar kelenteng diatas, agama apa yang menggunakan tempat ibadah tersebut adalah …….",
        options: ["Islam", "Budha", "Konghucu", "Hindu"],
        answer: "C",
        img: "PKN-24.webp",
      },
      {
        q: "Perhatikan pernyataan-pernyataan di bawah ini!\n1. Membersihkan halaman rumah masing-masing.\n2. Membantu tetangga yang sedang mengadakan hajatan.\n3. Melaksanakan tugas piket kebersihan kelas.\n4. Memperbaiki jembatan desa yang rusak secara bersama-sama.\n5. Mengikuti kegiatan siskamling (ronda malam).\nBerdasarkan pernyataan di atas, contoh kegiatan gotong royong di lingkungan masyarakat ditunjukkan oleh nomor ....",
        options: ["1, 2, dan 3", "2, 4, dan 5", "1, 3, dan 4", "3, 4, dan 5"],
        answer: "B",
      },
      {
        q: "Kepanjangan dari PPKI adalah ....",
        options: [
          "Panitia Persiapan Kemerdekaan Indonesia",
          "Panitia Persiapan Kemerdekaan Islam",
          "Panitia Persatuan Kemerdekaan Indonesia",
          "Panitia Pembentukan Kemerdekaan Indonesia",
        ],
        answer: "A",
      },
      {
        q: "Bunyi Pasal 27 ayat (2) UUD 1945 adalah ....",
        options: [
          "Setiap warga negara berhak mendapat pendidikan",
          "Tiap-tiap warga negara berhak atas pekerjaan dan penghidupan yang layak bagi kemanusiaan",
          "Kemerdekaan berserikat dan berkumpul",
          "Fakir miskin dipelihara oleh negara",
        ],
        answer: "B",
      },
      {
        q: "Kegiatan kerja bakti membersihkan lingkungan sekolah mencerminkan sila ke ....",
        options: ["Pertama", "Kedua", "Ketiga", "Kelima"],
        answer: "C",
      },
      {
        q: "Sanksi bagi pelanggar norma kesopanan adalah ....",
        options: [
          "Dipenjara",
          "Dikucilkan masyarakat",
          "Mendapat dosa",
          "Didenda",
        ],
        answer: "B",
      },
      {
        q: "Kewajiban adalah ....",
        options: [
          "Sesuatu yang harus diterima",
          "Sesuatu yang harus dilakukan dengan penuh tanggung jawab",
          "Sesuatu yang menyenangkan",
          "Sesuatu yang dimiliki sejak lahir",
        ],
        answer: "B",
      },
      {
        q: "Musyawarah yang dilakukan bersama untuk mencapai keputusan bersama disebut ....",
        options: ["Perselisihan", "Pertengkaran", "Mufakat", "Kompetisi"],
        answer: "C",
      },
      {
        q: "Kelenteng merupakan tempat ibadah umat agama ....",
        options: ["Islam", "Hindu", "Buddha", "Konghucu"],
        answer: "D",
      },
      {
        q: "Bangunan khas dari Provinsi DKI Jakarta adalah ....",
        options: [
          "Jam Gadang",
          "Monumen Nasional (Monas)",
          "Lawang Sewu",
          "Gedung Sate",
        ],
        answer: "B",
      },
      {
        q: "Makanan khas dari Madura adalah ....",
        options: ["Rendang", "Gudeg", "Sate Madura", "Pempek"],
        answer: "C",
      },
      {
        q: "Manfaat gotong royong adalah ....",
        options: [
          "Pekerjaan menjadi lebih berat",
          "Menambah perselisihan",
          "Pekerjaan cepat selesai",
          "Membuat masyarakat malas",
        ],
        answer: "C",
      },
      {
        q: "Rumusan dasar negara menurut Moh. Yamin secara lisan salah satunya adalah ....",
        options: [
          "Ketuhanan Yang Maha Esa",
          "Peri Kebangsaan",
          "Persatuan Indonesia",
          "Keadilan sosial bagi seluruh rakyat Indonesia",
        ],
        answer: "B",
      },
      {
        q: "Ibu kota Provinsi Jawa Barat adalah ....",
        options: ["Serang", "Bandung", "Semarang", "Surabaya"],
        answer: "B",
      },
      {
        q: "Nilai yang terkandung dalam sila kedua Pancasila adalah ....",
        options: [
          "Mengutamakan persatuan",
          "Menghargai sesama manusia",
          "Rajin bermusyawarah",
          "Menjaga kebersihan lingkungan",
        ],
        answer: "B",
      },
      {
        q: "Norma yang bersumber dari hati nurani disebut norma ....",
        options: ["Agama", "Kesusilaan", "Kesopanan", "Hukum"],
        answer: "B",
      },
      {
        q: "Berikut yang mencerminkan persatuan dan kesatuan adalah ....",
        options: [
          "Memilih teman",
          "Bertengkar dengan tetangga",
          "Kerja bakti membersihkan lingkungan",
          "Mengejek budaya daerah lain",
        ],
        answer: "C",
      },
      {
        q: "Salah satu rumusan dasar negara menurut Moh. Yamin adalah ....",
        options: [
          "Peri Kemanusiaan",
          "Demokrasi",
          "Sosialisme",
          "Nasionalisme sempit",
        ],
        answer: "A",
      },
      {
        q: "Ibu kota Provinsi Jawa Tengah adalah ....",
        options: ["Bandung", "Semarang", "Surabaya", "Denpasar"],
        answer: "B",
      },
      {
        q: "Ibu kota Provinsi Sumatera Utara adalah ....",
        options: ["Padang", "Pekanbaru", "Medan", "Palembang"],
        answer: "C",
      },
      {
        q: "Setiap hari Minggu, warga Kampung Sukamaju bekerja bersama membersihkan lingkungan dan memperbaiki jalan yang rusak tanpa membeda-bedakan satu sama lain. Sikap tersebut mencerminkan pengamalan sila ....",
        options: ["Pertama", "Kedua", "Ketiga", "Kelima"],
        answer: "C",
      },
      {
        q: "Salah satu nilai Pancasila sila keempat adalah ....",
        options: [
          "Menghormati hasil musyawarah",
          "Suka memaksakan kehendak",
          "Bersikap egois",
          "Tidak peduli terhadap orang lain",
        ],
        answer: "A",
      },
      {
        q: "Rizki berbicara kasar kepada orang yang lebih tua dan tidak meminta maaf setelah berbuat salah. Akibat perbuatannya, teman-teman dan warga di sekitarnya menjadi tidak suka kepadanya. Berdasarkan cerita tersebut, orang yang melanggar norma kesopanan biasanya akan mendapat ....",
        options: ["Pujian", "Penghargaan", "Celaan dari masyarakat", "Hadiah"],
        answer: "C",
      },
      {
        q: "Raid tertangkap polisi karena mengambil barang milik orang lain tanpa izin. Perbuatan tersebut termasuk pelanggaran norma hukum. Sanksi yang dapat diterima Raid adalah ....",
        options: [
          "Rasa malu",
          "Penyesalan",
          "Hukuman pidana",
          "Dikucilkan teman",
        ],
        answer: "C",
      },
      {
        q: "Keputusan hasil musyawarah harus dilaksanakan dengan ....",
        options: ["Terpaksa", "Tanggung jawab", "Marah-marah", "Acuh tak acuh"],
        answer: "B",
      },
      {
        q: "Mesjid adalah tempat ibadah agama ....",
        options: ["Hindu", "Islam", "Konghucu", "Kristen"],
        answer: "B",
      },
      {
        q: "Contoh gotong royong di masyarakat adalah ....",
        options: [
          "Bermain sendiri di rumah",
          "Membersihkan selokan bersama warga",
          "Belajar sendiri",
          "Berjualan di pasar",
        ],
        answer: "B",
      },
    ],
  },
  {
    id: "MTK",
    title: "Matematika",
    classDefault: "Kelas 6 (Aqaba)",
    duration: 90,
    theme: "from-blue-500 to-indigo-500",
    secure: "1256",
    questions: [
      {
        q: "Bilangan 255.955.000 dibaca………",
        options: [
          "Dua ratus lima puluh lima juta sembilan ratus lima puluh ribu",
          "Dua ratus lima puluh lima juta sembilan ratus lima puluh lima ribu",
          "Dua ratus lima puluh lima juta delapan ratus lima puluh lima ribu",
          "Dua ratus lima puluh lima juta sembilan ratus lima ribu",
        ],
        answer: "B",
      },
      {
        q: "Perhatikan gambar berikut!\nPecahan senilai yang sesuai dengan gambar adalah …",
        options: ["2/4", "1/8", "1/4", "1/2"],
        answer: "C",
        img: "MTK-2.webp",
      },
      {
        q: "Ibu Nurul membuat 3 kue pizza. Ketika kue pizza sudah matang, ibu Nurul memotongnya seperti tampak pada gambar.\nPizza A dipotong menjadi 2 bagian yang sama besar. Pizza B dipotong menjadi 3 bagian yang sama besar. Pizza C dipotong menjadi 4 bagian yang sama besar. Pernyataan yang benar adalah ....",
        options: [
          "Potongan pizza A lebih kecil dibandingkan dengan potongan pizza C",
          "Potongan pizza A lebih besar dibandingkan dengan potongan pizza B",
          "Potongan pizza B lebih besar dibandingkan dengan potongan pizza A",
          "Potongan pizza C lebih besar dibandingkan dengan potongan pizza B",
        ],
        answer: "B",
        img: "MTK-3.webp",
      },
      {
        q: "Perpustakaan memiliki 84 buku.\nBuku-buku tersebut akan disusun ke dalam beberapa rak.\nSetiap rak harus berisi jumlah buku yang sama.\nJika ada 7 rak, maka setiap rak berisi … buku.",
        options: ["10", "11", "12", "13"],
        answer: "C",
      },
      {
        q: "Besar sudut yang terbentuk pada jarum jam berikut adalah … derajat.",
        options: ["30", "90", "45", "180"],
        answer: "B",
        img: "MTK-5.webp",
      },
      {
        q: "Faktor prima dari 24 adalah …",
        options: ["2 dan 3", "3 dan 5", "1 dan 2", "3 dan 7"],
        answer: "A",
      },
      {
        q: "Diketahui dua buah bilangan yaitu 12 dan 18.\nTentukan Kelipatan Persekutuan Terkecil (KPK) dari kedua bilangan tersebut!",
        options: ["24", "30", "36", "48"],
        answer: "C",
      },
      {
        q: "Diketahui dua buah bilangan yaitu 24 dan 36.\nTentukan Faktor Persekutuan Terbesar (FPB) dari kedua bilangan tersebut!",
        options: ["6", "8", "12", "18"],
        answer: "C",
      },
      {
        q: "Sebuah segitiga sama sisi memiliki panjang sisi 12 cm. Keliling segitiga tersebut adalah…",
        options: ["24 cm", "48 cm", "144 cm", "36 cm"],
        answer: "D",
      },
      {
        q: "Sisi sebuah kertas lipat berbentuk persegi adalah 15 cm. Berapakah luas kertas tersebut?",
        options: ["60", "150", "30", "225"],
        answer: "D",
      },
      {
        q: "Perhatikan gambar berikut.\nBerapakah hasil perkalian dari gambar pecahan di atas?",
        options: [
          "3/4 * 2 = 6/8",
          "3/4 * 3 = 9/4",
          "3/4 * 3/4 = 9/16",
          "3/4 * 2 = 8/3",
        ],
        answer: "A",
        img: "MTK-11.webp",
      },
      {
        q: "Hasil dari 3/4 ÷ 2 adalah",
        options: ["3/8", "6/4", "2/3", "4/3"],
        answer: "A",
      },
      {
        q: "Perhatikan tabel berikut !\nBerdasarkan tabel di atas, yang memiliki rasio sama dengan 2:3 adalah nomor …",
        options: ["1", "2", "3", "4"],
        answer: "D",
        img: "MTK-13.webp",
      },
      {
        q: "Mbak Tina membeli beberapa jenis buah-buahan, diantaranya:\nRasio dari buah apel dan pir adalah …",
        options: ["3 : 4", "2 : 5", "4 : 5", "4 : 3"],
        answer: "C",
        img: "MTK-14.webp",
      },
      {
        q: "Sebuah taman berbentuk persegi memiliki panjang sisi 12 cm. Luas taman tersebut adalah...",
        options: ["24 cm²", "48 cm²", "144 cm²", "169 cm²"],
        answer: "C",
      },
      {
        q: "Perhatikan beberapa pernyataan tentang sifat bangun ruang berikut!\n    1) Memiliki 6 sisi yang semuanya berbentuk persegi dengan ukuran yang sama.\n    2) Memiliki 12 rusuk yang terdiri dari 3 kelompok rusuk yang sejajar dan sama panjang.\n    3) Memiliki 8 titik sudut.\n    4) Memiliki 12 rusuk yang semuanya sama panjang.\n    5) Memiliki sisi-sisi yang berhadapan sejajar dan sama luas, tetapi tidak semua sisinya harus berbentuk persegi.\nBerdasarkan pernyataan di atas, yang merupakan sifat khusus dari bangun ruang kubus ditunjukkan oleh nomor…",
        options: ["1, 2, dan 3", "1, 3, dan 4", "2, 3, dan 5", "3, 4, dan 5"],
        answer: "B",
      },
      {
        q: "Perhatikan gambar berkut!\nJumlah seluruh kubus pada susunan tersebut adalah ….",
        options: ["6 kubus", "7 kubus", "8 kubus", "9 kubus"],
        answer: "B",
        img: "MTK-17.webp",
      },
      {
        q: "Berdasarkan gambar diatas, jumlah titik yang tampak pada dadu berjumlah….",
        options: ["2", "7", "9", "11"],
        answer: "B",
        img: "MTK-18.webp",
      },
      {
        q: "Perhatikan gambar berikut!",
        options: ["Gambar A", "Gambar B", "Gambar C", "Gambar D"],
        answer: "A",
        img: "MTK-19.webp",
      },
      {
        q: "Sebuah kantong berisi 5 bola merah dan 3 bola biru.\nJika diambil satu bola secara acak, maka peluang terambil bola merah adalah ....",
        options: ["3/8", "5/8", "1/5", "1/4"],
        answer: "B",
      },
      {
        q: "Terdapat beberapa buku dengan warna berbeda, yaitu 4 buku merah, 2 buku kuning, dan 3 buku hijau.\nBerdasarkan gambar tersebut, peluang paling besar untuk terambil adalah buku berwarna ....",
        options: ["Kuning", "Hijau", "Merah", "Semua Sama"],
        answer: "C",
      },
      {
        q: "Suatu kolam berbentuk balok mempunyai panjang 30 dm, lebar 18 dm, dan tinggi 10 dm. Jika kolam itu berisi air sebanyak ¾ bagian, volume air yang ada dalam kolam adalah ..",
        options: ["5.400 Liter", "4.050 Liter", "2.700 Liter", "1.350 Liter"],
        answer: "B",
      },
      {
        q: "Perhatikan pernytaan berikut!\nBeruang mulai berhibernasi pada musim panas\nBerdasarkan skala peluang, kejadian di atas dikelompokkan ke dalam katagori ….",
        options: ["Pasti", "Sangat Mungkin", "Kurang Mungkin", "Tidak Mungkin"],
        answer: "D",
      },
      {
        q: "Seorang siswa akan mengambil satu buah buku secara acak dari dalam rak tersebut. \nBerdasarkan gambar, kejadian mana yang memiliki peluang paling besar?",
        options: [
          "Terambilnya buku berwarna kuning",
          "Terambilnya buku berwarna merah",
          "Terambilnya buku berwarna hijau",
          "Terambilnya buku berwarna biru",
        ],
        answer: "B",
        img: "MTK-24.webp",
      },
      {
        q: "Perhatikan tabel hasil percobaan pengambilan bola berwarna dalam sebuah kantong di bawah ini!\nBerdasarkan tabel di atas, peluang terambilnya bola berwarna kuning adalah ....",
        options: ["12/30", "12/40", "10/30", "10/40"],
        answer: "B",
        img: "MTK-25.webp",
      },
      {
        q: "Bu Nida memiliki 96 buku cerita yang akan dibagikan sama banyak kepada 8 siswa berprestasi. Setiap siswa kemudian meminjamkan 3 bukunya kepada teman lain. Banyak buku yang masih dimiliki setiap siswa adalah ....",
        options: ["6 buku", "9 buku", "12 buku", "15 buku"],
        answer: "B",
      },
      {
        q: "Hasil dari 240 ÷ 6 × (15 - 11) + 8 adalah ....",
        options: ["148", "160", "168", "176"],
        answer: "C",
      },
      {
        q: "Pada pukul 03.00, jarum pendek berada di angka 3 dan jarum panjang di angka 12. Besar sudut yang terbentuk adalah ....",
        options: ["45°", "60°", "90°", "180°"],
        answer: "C",
      },
      {
        q: "Pecahan 7/20 jika diubah ke bentuk desimal menjadi ....",
        options: ["0,25", "0,35", "0,7", "3,5"],
        answer: "B",
      },
      {
        q: "Perhatikan bilangan desimal berikut!\n0,8 ; 0,25 ; 0,75 ; 0,5\nUrutan dari yang terkecil ke terbesar adalah ....",
        options: [
          "0,25 ; 0,5 ; 0,75 ; 0,8",
          "0,25 ; 0,75 ; 0,5 ; 0,8",
          "0,5 ; 0,25 ; 0,75 ; 0,8",
          "0,8 ; 0,75 ; 0,5 ; 0,25",
        ],
        answer: "A",
      },
      {
        q: "Sebuah bangun tersusun dari kubus satuan seperti berikut:\nLapisan bawah terdiri atas 9 kubus dan lapisan atas terdiri atas 4 kubus. Jumlah seluruh kubus adalah ....",
        options: ["11", "12", "13", "14"],
        answer: "C",
      },
      {
        q: "Sebuah benda berbentuk huruf L dilihat dari atas tampak seperti ....",
        options: ["Persegi panjang", "Huruf L", "Segitiga", "Lingkaran"],
        answer: "B",
      },
      {
        q: "Sebuah kubus memiliki panjang rusuk 6 cm. Volume kubus tersebut adalah ....",
        options: ["36 cm³", "72 cm³", "108 cm³", "216 cm³"],
        answer: "D",
      },
      {
        q: "Perhatikan denah berikut!\nSekolah berada 3 petak ke timur dari pasar dan 2 petak ke utara dari taman. Letak sekolah yang tepat adalah ....",
        options: [
          "Barat daya taman",
          "Timur laut taman",
          "Tenggara pasar",
          "Barat laut pasar",
        ],
        answer: "B",
      },
      {
        q: "Dalam sebuah kantong terdapat 5 bola merah, 3 bola biru, dan 2 bola hijau. Bola yang paling besar peluangnya terambil adalah ....",
        options: ["Bola hijau", "Bola biru", "Bola merah", "Semua sama besar"],
        answer: "C",
      },
      {
        q: "Pak Dedi membeli 5 kotak pensil. Setiap kotak berisi 12 pensil. Sebanyak 8 pensil diberikan kepada adiknya. Banyak pensil Pak Dedi sekarang adalah ....",
        options: ["48", "50", "52", "60"],
        answer: "C",
      },
      {
        q: "Lampu merah menyala setiap 6 detik dan lampu hijau menyala setiap 8 detik. Jika keduanya menyala bersama pukul 19.00, keduanya akan menyala bersama lagi setelah ....",
        options: ["12 detik", "18 detik", "24 detik", "48 detik"],
        answer: "C",
      },
      {
        q: "Perbandingan siswa laki-laki dan perempuan di kelas VI adalah 3 : 5. Jika jumlah siswa perempuan 20 orang, banyak siswa laki-laki adalah ....",
        options: ["10 orang", "12 orang", "15 orang", "18 orang"],
        answer: "B",
      },
      {
        q: "Pada peta, rumah Fajri berada di titik A dan sekolah di titik B. Jarak kedua titik adalah 8 petak. Jika 1 petak mewakili 100 meter, maka jarak sebenarnya adalah ....",
        options: ["200 meter", "400 meter", "600 meter", "800 meter"],
        answer: "D",
      },
      {
        q: "Dalam sebuah kotak terdapat kartu angka 1 sampai 10. Peluang munculnya angka genap adalah ....",
        options: ["1/10", "2/10", "5/10", "8/10"],
        answer: "C",
      },
      {
        q: "Sebuah roda putar memiliki 8 bagian sama besar terdiri atas 3 warna merah, 2 biru, 2 kuning, dan 1 hijau. Peluang terbesar saat roda diputar adalah mendapatkan warna ....",
        options: ["Hijau", "Biru", "Kuning", "Merah"],
        answer: "D",
      },
      {
        q: "Sebuah persegi memiliki sisi 15 cm. Luas persegi tersebut adalah ....",
        options: ["30 cm²", "60 cm²", "120 cm²", "225 cm²"],
        answer: "D",
      },
      {
        q: "Halaman sekolah berbentuk persegi dengan panjang sisi 20 meter. Luas halaman tersebut adalah ....",
        options: ["200 m²", "300 m²", "400 m²", "800 m²"],
        answer: "C",
      },
      {
        q: "Perbandingan umur Fakhrie dan Siska adalah 4 : 5. Jika umur Dina 12 tahun, umur Siska adalah ....",
        options: ["14 tahun", "15 tahun", "16 tahun", "18 tahun"],
        answer: "B",
      },
      {
        q: "Sebuah persegi panjang memiliki panjang 18 cm dan lebar 12 cm. Keliling bangun tersebut adalah ....",
        options: ["30 cm", "48 cm", "60 cm", "216 cm"],
        answer: "C",
      },
      {
        q: "Ibu mempunyai 3/4 kg gula. Gula tersebut digunakan sebanyak 2 × 1/8 kg untuk membuat kue. Sisa gula ibu adalah ....",
        options: ["1/4 kg", "1/2 kg", "3/8 kg", "5/8 kg"],
        answer: "B",
      },
      {
        q: "Sebuah segitiga memiliki sisi 12 cm, 15 cm, dan 17 cm. Keliling segitiga tersebut adalah ....",
        options: ["34 cm", "42 cm", "44 cm", "46 cm"],
        answer: "C",
      },
      {
        q: "KPK dari 12 dan 18 adalah ....",
        options: ["24", "30", "36", "48"],
        answer: "C",
      },
      {
        q: "Perhatikan dua pecahan berikut!\n3/4 dan 5/8\nPecahan yang lebih besar adalah ....",
        options: ["3/4", "5/8", "Keduanya sama", "Tidak dapat dibandingkan"],
        answer: "A",
      },
      {
        q: "Sebuah pizza dibagi menjadi 8 bagian sama besar. Rina memakan 3 bagian dan Siti memakan 2 bagian. Pecahan pizza yang sudah dimakan adalah ....",
        options: ["3/8", "2/8", "5/8", "7/8"],
        answer: "C",
      },
    ],
  },
  {
    id: "BINDO",
    title: "Bahasa Indonesia",
    classDefault: "Kelas 6 (Aqaba)",
    duration: 90,
    theme: "from-green-500 to-emerald-500",
    secure: "9865",
    questions: [
      {
        q: "Perhatikan kalimat berikut:\n1). Budi membaca Al-Qur’an\n2.) Adik tidur \n3.) Ibu memasak sayur\n4.) Ayah mencuci mobil\n5.) Burung terbang\n6.) Siswa mengerjakan PR\nContoh kalimat transitif ditunjukkan oleh nomer ….",
        options: [
          "1), 2) , 3), 4)",
          "2), 3), 4), 5)",
          "1), 3), 4), 6)",
          "3), 4), 5), 6)",
        ],
        answer: "C",
      },
      {
        q: "Kalimat berikut yang termasuk kalimat intransitif adalah..",
        options: [
          "Rizan membaca buku",
          "Ayah memperbaiki sepeda",
          "Adik menangis",
          "Ibu memasak nasi",
        ],
        answer: "C",
      },
      {
        q: "Calista menulis surat di atas meja. Manakah kata yang berfungsi sebagai subjek dari kalimat di atas?",
        options: ["Calista", "Menulis", "Surat", "Di Atas Meja"],
        answer: "A",
      },
      {
        q: "Firas bermain handphone.\nKalimat tersebut menggunakan pola…..",
        options: [
          "Subjek - Predikat - Objek - Keterangan ( SPOK )",
          "Subjek - Predikat - Keterangan ( SPK )",
          "Subjek - Predikat - Objek ( SPO )",
          "Objek - Predikat - Subjek ( OPS )",
        ],
        answer: "C",
      },
      {
        q: "Perhatikan kalimat berikut ini !\nUlar kobra memiliki bisa yang mematikan.\nAndi bisa mengerjakan tugas dengan baik.\nKata bisa pada kalimat pertama memiliki arti …",
        options: ["dapat", "racun", "mampu", "sanggup"],
        answer: "B",
      },
      {
        q: "Pak Alwi menyampaikan bahwa hari Senin akan diadakan ulangan harian\nTanda baca yang tepat untuk melengkapi kalimat di atas adalah …",
        options: ["Titik (.)", "Koma (,)", "Seru (!)", "Tanda Tanya (?)"],
        answer: "A",
      },
      {
        q: "Perhatikan pernyataan berikut!\n(1) Manusia membutuhkan air untuk hidup.\n(2) Air putih lebih enak daripada minuman lainnya.\nInformasi yang termasuk fakta adalah ….",
        options: ["1", "2", "1 dan 2", "Tidak Ada"],
        answer: "A",
      },
      {
        q: "Perhatikan kalimat berikut!\nIbu sedang memasak di dapur.\nKata berimbuhan me- pada kalimat tersebut adalah ….",
        options: ["Ibu", "Sedang", "Memasak", "Dapur"],
        answer: "C",
      },
      {
        q: "Iklan yang dibuat oleh pemerintah atau organisasi tertentu dengan tujuan untuk memberikan penerangan, edukasi, atau imbauan kepada masyarakat tanpa mencari keuntungan disebut…",
        options: [
          "Iklan Baris",
          "Iklan Penawaran",
          "Iklan Niaga",
          "Iklan Layanan Masyarakat",
        ],
        answer: "D",
      },
      {
        q: "Bacalah ringkasan berikut!\nSheenaz sangat giat berlatih tari Pendet setiap sore. Ia ingin menunjukkan keindahan budaya Bali saat pertukaran pelajar nanti. Ayahnya selalu mendukung dengan membelikan perlengkapan tari yang dibutuhkan.\nSiapakah tokoh utama yang diceritakan memiliki semangat melestarikan budaya dalam teks tersebut?",
        options: ["Guru Tari", "Pelajar Bali", "Ayah Sheenaz", "Sheenaz"],
        answer: "D",
      },
      {
        q: "Tokoh utama yang menjadi pusat perhatian dalam cerita dan biasanya digambarkan dengan sifat-sifat baik disebut ….",
        options: ["Antagonis", "Tritagonis", "Protagonis", "Figuran"],
        answer: "C",
      },
      {
        q: "Fadhli ingin mengisi formulir pendaftaran peminjaman buku perpustakaan dengan data acak sebagai berikut:\n(1) Nama\n(2) Kelas\n(3) Alamat\n(4) Tanggal Lahir\nPengisian data formulir yang tepat adalah ….",
        options: ["1-2-4-3", "1-3-2-4", "1-4-3-2", "1-4-2-3"],
        answer: "D",
      },
      {
        q: "Perhatikan pernyataan-pernyataan di bawah ini!\n1) Memerlukan perangko dan kotak pos untuk pengirimannya.\n2) Surat dikirimkan melalui jaringan internet menggunakan perangkat komputer atau ponsel pintar.\n3) Membutuhkan waktu beberapa hari agar surat sampai ke alamat tujuan.\n4) Pesan dapat terkirim dan diterima secara langsung (instan) dalam hitungan detik.\n5) Alamat tujuan ditulis dalam format khusus seperti nama@penyedia.com.\nBerdasarkan pernyataan di atas, ciri khas dan makna dari surat elektronik (e-mail) yang tepat ditunjukkan oleh nomor…",
        options: ["1,2, dan 3", "1,3, dan 5", "2,4, dan 5", "3,4, dan 5"],
        answer: "C",
      },
      {
        q: 'Bacalah kutipan artikel di bawah ini dengan cermat!\n"Dunia internasional kini semakin mengenal bakat dari Indonesia. Salah satu pianis muda berbakat asal Jakarta telah berhasil menembus panggung musik jazz dunia di Amerika Serikat. Sejak usia dini, ia sudah menunjukkan kemampuan luar biasa dalam bermain piano. Prestasi puncaknya adalah ketika ia berhasil masuk dalam nominasi penghargaan musik paling bergengsi di dunia, yaitu Grammy Awards, untuk kategori album jazz terbaik."\nBerdasarkan kutipan artikel di atas, siapakah sosok musisi Indonesia yang dimaksud?',
        options: [
          "Isyana Sarasvati",
          "Joey Alexander",
          "Sandhy Sondoro",
          "Rich Brian",
        ],
        answer: "B",
      },
      {
        q: "Cerita Malin Kundang mengisahkan seorang anak yang durhaka kepada ibunya setelah ia menjadi kaya. Akibatnya, ia dikutuk menjadi batu. cerita ini sering dinasehatkan oleh orang tua kepada anak-anaknya. Mengapa cerita Malin Kundang masih relevan dan penting untuk diceritakan hingga saat ini?",
        options: [
          "Karena cerita tersebut berasal dari Sumatera Barat.",
          "Agar anak-anak takut pergi merantau.",
          "Karena kutukan menjadi batu benar-benar bisa terjadi.",
          "Untuk mengajarkan pentingnya menghormati dan menyayangi orang tua",
        ],
        answer: "D",
      },
      {
        q: "Perhatikan kalimat berikut (1) Indonesia merdeka pada tanggal 17 Agustus 1945. (2) Menurut saya, Indonesia adalah negara yang paling indah. Kalimat yang merupakan Fakta adalah..",
        options: [
          "Kalimat 1",
          "Kalimat 2",
          "Kalimat 1 dan 2",
          "Tidak Ada yang Fakta",
        ],
        answer: "A",
      },
      {
        q: "Perhatikan pernyataan berikut!\n (1) Menyusun daftar pertanyaan\n (2) Menentukan tujuan wawancara\n (3) Menentukan narasumber\n (4) Mempelajari topik yang akan dibahas\nUrutan yang tepat langkah-langkah yang perlu dilakukan sebelum melakukan wawancara adalah ….",
        options: [
          "(2) – (3) – (4) – (1)",
          "(3) – (2) – (1) – (4)",
          "(4) – (2) – (3) – (1)",
          "(2) – (4) – (3) – (1)",
        ],
        answer: "A",
      },
      {
        q: "Perhatikan kalimat berikut!\n “Air mata ibu mengalir seperti sungai yang tak pernah kering saat melepas kepergian anaknya.”\n Majas yang tepat digunakan dalam kalimat tersebut adalah ….",
        options: ["personifikasi", "Metafora", "Hiperbola", "Simile"],
        answer: "D",
      },
      {
        q: "“Ibu selalu menasehati kami agar tidak hidup seperti katak dalam tempurung.”\nMakna majas asosiasi pada kalimat di atas adalah ….",
        options: [
          "Orang yang memiliki wawasan sangat sempit namun merasa tahu segalanya",
          "Sesorang yang lincah dan pandai melompat ke sana kemari",
          "Orang yang selalu merasa ketakutan dan bersembunyi di tempat gelap",
          "Seseorang yang hidupnya selalu berpindah - pindah tempat tinggal",
        ],
        answer: "A",
      },
      {
        q: "“Suara gemuruh awan kelabu menggema di langit.”\nMajas yang digunakan dalam kalimat di atas adalah …..",
        options: ["personifikasi", "Metafora", "Hiperbola", "Onomatope"],
        answer: "D",
      },
      {
        q: "Walaupun berasal dari keluarga tidak mampu, arman tidak pernah patah arang. ia belajar dengan giat setiap malam agar bisa mendapatkan beasiswa ke sekolah favoritnya. Makna ungkapan “Patah Arang” adalah…",
        options: [
          "Putus Asa",
          "Kehabisan Akal",
          "Tidak Bersemangat",
          "Sakit Hati",
        ],
        answer: "A",
      },
      {
        q: ' "Harga kebutuhan pokok di pasar tradisional mengalami kenaikan yang signifikan menjelang hari raya."\nAntonim dari kata kenaikan pada kalimat tersebut adalah ....',
        options: ["Penurunan", "Peningkatan", "Perbaikan", "Perubahan"],
        answer: "A",
      },
      {
        q: 'Perhatikan pernyataan berikut:\n Kata "indah" memiliki makna yang sama dengan kata "elok".\nBerdasarkan pernyataan tersebut, kata yang bersinonim dengan kata indah adalah ....',
        options: ["Buruk", "Cantik", "Rusak", "Kusam"],
        answer: "B",
      },
      {
        q: 'Bacalah ringkasan pidato berikut!\n"Teman-teman sekalian, marilah kita mulai menjaga kebersihan lingkungan sekolah dari hal yang paling kecil, yaitu membuang sampah pada tempatnya. Dengan lingkungan yang bersih, belajar pun akan menjadi lebih nyaman. Akhir kata, mohon maaf jika ada perkataan saya yang kurang berkenan. Terima kasih atas perhatiannya."\nBagian teks pidato tersebut merupakan ...',
        options: ["Pembukaan", "Isi", "Penutup", "Pendahuluan"],
        answer: "C",
      },
      {
        q: "Albi menjadi buah bibir di sekolahnya setelah memenangkan lomba pidato tingkat nasional. Arti ungkapan “buah bibir” dalam kalimat tersebut adalah ….",
        options: [
          "Bibir yang manis",
          "Bahan pembicaraan orang banyak",
          "Hadiah berupa buah",
          "Sesuatu yang dimakan",
        ],
        answer: "B",
      },
      {
        q: "Perhatikan kalimat berikut!\n1.\tIbu memasak sayur di dapur.\n2.\tAdik tidur nyenyak di kamar.\n3.\tKakak menendang bola ke arah gawang.\n4.\tBurung-burung beterbangan di langit.\nKalimat yang termasuk kalimat transitif ditunjukkan oleh nomor ....",
        options: ["1 dan 2", "1 dan 3", "2 dan 4", "3 dan 4"],
        answer: "B",
      },
      {
        q: "Perhatikan kalimat berikut!\n“Pada musim hujan, banyak warga mengalami banjir karena sungai meluap.”\nKata “banjir” pada kalimat tersebut memiliki makna yang berbeda dengan kalimat ....",
        options: [
          "Desa itu banjir bantuan dari para donatur.",
          "Air sungai meluap hingga menyebabkan banjir besar.",
          "Jalan raya tergenang akibat banjir semalam.",
          "Rumah warga rusak diterjang banjir bandang.",
        ],
        answer: "A",
      },
      {
        q: "Mala ingin melengkapi kalimat berikut.\n“Ibu sedang .... pakaian di halaman rumah agar cepat kering.”\nKata berimbuhan me- yang tepat untuk melengkapi kalimat tersebut adalah ....",
        options: ["Menjemur", "Jemuran", "Dijemur", "terjemur"],
        answer: "A",
      },
      {
        q: "Antonim kata “hemat” pada kalimat “Aliciea anak yang hemat dalam menggunakan uang saku” adalah ....",
        options: ["Rajin", "Boros", "Pelit", "Sederhana"],
        answer: "B",
      },
      {
        q: "Perhatikan kalimat berikut!\n“Globalisasi membuat informasi dari berbagai negara dapat diketahui dengan cepat.”\nMakna kata “globalisasi” pada kalimat tersebut adalah ....",
        options: [
          "perpindahan penduduk",
          "kerja sama antarwarga",
          "mendunianya suatu hal",
          "kegiatan jual beli di pasar",
        ],
        answer: "C",
      },
      {
        q: "Perhatikan bagian surat berikut!\nTasikmalaya, 12 Mei 2026\nBagian surat resmi tersebut disebut ....",
        options: [
          "Salam Pembuka",
          "Kepala Surat",
          "Tempat dan Tanggal Surat",
          "Isi Surat",
        ],
        answer: "C",
      },
      {
        q: "Bacalah pernyataan berikut!\n“Wawancara yang ditulis kembali dalam bentuk percakapan lengkap disebut transkrip wawancara.”\nMakna dari transkrip wawancara adalah ....",
        options: [
          "hasil pidato narasumber",
          "catatan singkat wawancara",
          "rekaman suara wawancara",
          "hasil penulisan kembali wawancara secara lengkap",
        ],
        answer: "D",
      },
      {
        q: "Perhatikan kalimat berikut!\n“Semangat para pemain itu membara saat pertandingan dimulai.”\nKalimat tersebut menggunakan majas ....",
        options: ["Hiperbola", "Metafora", "Personifikasi", "Asosiasi"],
        answer: "B",
      },
      {
        q: "Perhatikan kalimat berikut!\n“Menurut saya, membaca buku lebih menyenangkan daripada bermain gim sepanjang hari.”\nKalimat tersebut termasuk ....",
        options: ["Fakta", "Opini", "Perintah", "Saran"],
        answer: "B",
      },
      {
        q: "Perhatikan data pengunjung perpustakaan berikut!\nSenin : 20 siswa\nSelasa : 35 siswa\nRabu : 30 siswa\nKamis : 40 siswa\nBerdasarkan data tersebut, kesimpulan yang tepat adalah ....",
        options: [
          "Hari Senin paling banyak pengunjungnya",
          "Hari Kamis memiliki pengunjung terbanyak",
          "Hari Selasa paling sedikit pengunjungnya",
          "Jumlah pengunjung setiap hari sama",
        ],
        answer: "B",
      },
      {
        q: "Penulisan nilai uang yang tepat adalah ....",
        options: [
          "Rp15.000,00 (lima belas ribu rupiah)",
          "Rp.15.000 (lima belas ribu rupiah)",
          "15.000 rupiah",
          "Rp15,000.00",
        ],
        answer: "A",
      },
      {
        q: "Perhatikan idiom berikut!\n1.\tKambing hitam\n2.\tBuah tangan\n3.\tPanjang tangan\nMakna idiom “panjang tangan” adalah ....",
        options: [
          "Suka menolong",
          "Suka Mencuri",
          "Ringan Tangan",
          "Mudah Marah",
        ],
        answer: "B",
      },
      {
        q: "Berikut yang termasuk unsur surat resmi adalah ....",
        options: [
          "nama panggilan",
          "alamat teman",
          "nomor surat",
          "nama hewan peliharaan",
        ],
        answer: "C",
      },
      {
        q: "Perhatikan kalimat langsung berikut!\nAyah berkata, “Besok kita akan pergi ke rumah nenek.”\nKalimat tidak langsung yang tepat adalah ....",
        options: [
          "Ayah berkata bahwa besok kita akan pergi ke rumah nenek.",
          "Ayah berkata, besok kita akan pergi ke rumah nenek.",
          "“Besok kita akan pergi ke rumah nenek,” kata Ayah.",
          "Ayah mengatakan besok pergi rumah nenek.",
        ],
        answer: "A",
      },
      {
        q: "Perhatikan kutipan berikut!\n“Pendidikan adalah senjata paling ampuh untuk mengubah dunia.”\nTokoh yang terkenal dengan kutipan tersebut adalah ....",
        options: [
          "Ir. Soekarno",
          "B.J. Habibie",
          "Nelson Mandela",
          "Ki Hajar Dewantara",
        ],
        answer: "C",
      },
      {
        q: "Perhatikan kalimat berikut!\n“Nissa membaca buku cerita di perpustakaan.”\nPola kalimat tersebut adalah ....",
        options: ["SP", "SPO", "SPK", "SPOK"],
        answer: "D",
      },
      {
        q: "Perhatikan kalimat berikut!\n“Bunga desa itu menjadi bunga tidur bagiku.”\nMakna kata “bunga” yang berbeda ditunjukkan pada bagian ....",
        options: ["Bunga Desa", "Bunga Tidur", "Menjadi", "Bagiku"],
        answer: "B",
      },
      {
        q: "Perhatikan kalimat berikut!\n“Petani itu sedang .... sawah sejak pagi.”\nKata berimbuhan me- yang tepat adalah ....",
        options: ["Membajak", "Bajakan", "Dibajak", "Terbajak"],
        answer: "A",
      },
      {
        q: "Bacalah pernyataan berikut!\n“Air mendidih pada suhu 100°C.”\nPernyataan tersebut termasuk ....",
        options: ["Opini", "Khayalan", "Fakta", "Saran"],
        answer: "C",
      },
      {
        q: "Sebuah iklan berisi ajakan memakai helm saat berkendara untuk menjaga keselamatan. Jenis iklan tersebut adalah ....",
        options: [
          "Niaga",
          "Pelayanan Masyarakat",
          "Penawaran Barang",
          "Hiburan",
        ],
        answer: "B",
      },
      {
        q: "Antonim kata “tinggi” pada kalimat “Pohon itu sangat tinggi” adalah ....",
        options: ["Besar", "Pendek", "Luas", "Sempit"],
        answer: "B",
      },
      {
        q: "Perhatikan ciri-ciri berikut!\n1.\tMenggunakan bahasa santai\n2.\tDitujukan kepada teman atau keluarga\n3.\tMenggunakan bahasa resmi baku\nCiri surat pribadi ditunjukkan oleh nomor ....",
        options: ["1 dan 2", "1 dan 3", "2 dan 3", "1, 2, dan 3"],
        answer: "A",
      },
      {
        q: "Perhatikan kalimat berikut!\n“Suara penyanyi itu merdu seperti bulu perindu.”\nKalimat tersebut menggunakan majas ....",
        options: ["Hiperbola", "Metafora", "Asosiasi", "Personifikasi"],
        answer: "C",
      },
      {
        q: "Perhatikan kalimat berikut!\n“Menurutku, olahraga pagi adalah kegiatan paling menyenangkan.”\nKalimat tersebut termasuk ....",
        options: ["Fakta", "Opini", "Berita", "Pengumuman"],
        answer: "B",
      },
      {
        q: "Berikut yang merupakan ciri kalimat langsung adalah ....",
        options: [
          "Menggunakan kata penghubung bahwa",
          "Tidak memakai tanda petik",
          "Menirukan ucapan seseorang secara langsung",
          "Isi kalimat sudah diubah penulis",
        ],
        answer: "C",
      },
    ],
  },
  {
    id: "IPAS",
    title: "Ilmu Pengetahuan Alam",
    classDefault: "Kelas 6 (Aqaba)",
    duration: 90,
    theme: "from-slate-500 to-gray-500",
    secure: "9915",
    questions: [
      {
        q: "Perhatikan gambar berikut!\nBagian tumbuhan yang termasuk batang ditunjukkan oleh nomer….",
        img: "IPAS-1.webp",
        options: ["2", "3", "4", "5"],
        answer: "D",
      },
      {
        q: "Perhatikan gambar bunga berikut !\nBagian bunga yang ditunjuk dengan huruf B adalah ...",
        img: "IPAS-2.webp",
        options: ["Benang sari", "Kepala putik", "Mahkota bunga", "Bakal buah"],
        answer: "A",
      },
      {
        q: "Bagian bunga yang berfungsi sebagai alat kelamin betina adalah…",
        img: "",
        options: ["Benang sari", "Putik", "Kelopak", "Tangkai bunga"],
        answer: "B",
      },
      {
        q: "Perhatikan barang berikut:\n1. Rice cooker\n2. Sepeda Motor\n3. Makanan sehari-hari\n4. Tempat tinggal\nUrutan skala prioritas yang tepat adalah ....",
        img: "",
        options: [
          "3 → 4 → 1 → 2",
          "2 → 1 → 3 → 4",
          "1 → 2 → 3 → 4",
          "4 → 3 → 2 → 1",
        ],
        answer: "A",
      },
      {
        q: "Kamper atau kapur barus di dalam lemari semakin lama semakin habis. Hal itu menunjukkan perubahan wujud dari …",
        img: "",
        options: [
          "Padat menjadi cair",
          "Padat menjadi gas",
          "Cair menjadi gas",
          "Gas menjadi cair",
        ],
        answer: "B",
      },
      {
        q: "Perhatikan gambar bagian-bagian mata berikut ini !\nBagian mata yang di tunjuk panah pada gambar di atas adalah …",
        img: "IPAS-6.webp",
        options: ["Pupil", "Iris", "Skelra", "Retina"],
        answer: "A",
      },
      {
        q: "Perhatikan rantai makanan berikut!\nMakhluk hidup yang berperan sebagai konsumen tingkat I adalah ....",
        img: "IPAS-7.webp",
        options: ["Belalang", "Katak", "Rumput", "Elang"],
        answer: "C",
      },
      {
        q: "Perhatikan rantai makanan berikut!\nMakhluk hidup yang berperan sebagai produsen pada rantai makanan tersebut adalah ....",
        img: "IPAS-8.webp",
        options: ["Padi", "Tikus", "Ular", "Elang"],
        answer: "B",
      },
      {
        q: "Seorang siswa menggosokkan magnet batang pada sebuah paku besar secara berulang-ulang dengan arah yang tetap (searah). Setelah beberapa saat, paku tersebut dapat menarik klip kertas. Cara pembuatan magnet yang dilakukan siswa tersebut adalah…",
        img: "",
        options: ["Elektromagnetik", "Induksi", "Gosokan", "Konduksi"],
        answer: "C",
      },
      {
        q: "Bagian hidung yang berfungsi untuk menyaring kotoran yang masuk bersama udara pernapasan adalah…",
        img: "",
        options: [
          "Selaput Lendir",
          "Saraf Pembau",
          "Tulang Hidung",
          "Rambut Hidung",
        ],
        answer: "D",
      },
      {
        q: "Sendi peluru adalah sendi yang bisa bergerak kesegala arah. sendi peluru dapat kita lihat pada bagian ….",
        img: "",
        options: [
          "hubungan antara tulang lengan atas dengan gelang bahu",
          "hubungan antara tulang leher dengan tulang tengkorak",
          "Pergelangan tangan",
          "Pergelangan kaki",
        ],
        answer: "A",
      },
      {
        q: "Penyakit pada gambar di bawah diakibatkan karena …",
        img: "IPAS-12.webp",
        options: [
          "kekurangan Vitamin D",
          "kelainan sejak lahir atau kesalahan posisi duduk",
          "pengeroposan tulang",
          "kelebihan berat badan",
        ],
        answer: "B",
      },
      {
        q: "Perhatikan nama-nama negara berikut yang pernah datang ke Indonesia:\n1) Belanda\n2) Portugis\n3) Inggris\n4) Spanyol\nUrutan kedatangan bangsa Eropa ke Indonesia yang tepat adalah ....",
        img: "",
        options: [
          "Portugis -> Spanyol -> Belanda ->Inggris",
          "Spanyol -> Portugis -> Inggris -> Belanda",
          "Belanda -> Portugis -> Spanyol -> Inggris",
          "Portugis -> Belanda -> Spanyol -> Inggris",
        ],
        answer: "A",
      },
      {
        q: "Perhatikan negara-negara berikut!\n1) Brasil\n2) Kanada\n3) Jepang\n4) Argentina\nNegara yang berada di Benua Amerika ditunjukkan oleh nomor ....",
        img: "",
        options: ["1, 2, dan 3", "1, 2, dan 4", "1 dan 3", "2 dan 4"],
        answer: "B",
      },
      {
        q: "Benua Amerika merupakan salah satu benua terbesar di dunia. Negara yang terletak di Benua Amerika adalah ....",
        img: "",
        options: ["Thailand", "Italia", "Meksiko", "Mesir"],
        answer: "C",
      },
      {
        q: 'Perhatikan pernyataan mengenai aktivitas perdagangan internasional berikut!\n"Sebuah perusahaan mebel di Jepara, Jawa Tengah, mendapatkan pesanan kursi ukir dalam jumlah besar dari seorang pembeli yang berdomisili di Hamburg, Jerman. Setelah proses produksi selesai, barang tersebut dikirim melalui pelabuhan Tanjung Emas menuju pelabuhan tujuan di luar negeri."\nBerdasarkan ilustrasi di atas, aktivitas yang dilakukan oleh perusahaan mebel tersebut merupakan bentuk kegiatan…',
        img: "",
        options: [
          "Impor, karena perusahaan mengirimkan barang berkualitas ke luar negeri untuk memenuhi permintaan pasar global.",
          "Ekspor, karena merupakan kegiatan menjual atau mengirimkan barang produksi dalam negeri ke pasar luar negeri.",
          "Barter, karena terjadi pertukaran nilai antara pengrajin lokal dengan pembeli internasional di era globalisasi.",
          "Proteksi, karena pemerintah memfasilitasi pengiriman barang unggulan agar mampu bersaing di kancah dunia.",
        ],
        answer: "B",
      },
      {
        q: "Globalisasi adalah proses mendunianya berbagai aspek kehidupan akibat kemajuan teknologi, komunikasi, dan transportasi sehingga batas-batas antarnegara menjadi semakin sempit.\nDari pernyataan diatas manakah yang merupakan ciri globalisasi yang tepat?",
        img: "",
        options: [
          "Masyarakat hanya menggunakan produk dalam negeri",
          "Informasi dari berbagai negara sulit diperoleh",
          "Terjadinya pertukaran budaya antarnegara dengan mudah",
          "Hubungan antarnegara menjadi terbatas",
        ],
        answer: "C",
      },
      {
        q: "Kerja sama internasional adalah hubungan yang dilakukan oleh dua negara atau lebih untuk mencapai tujuan bersama di berbagai bidang, seperti ekonomi, sosial, budaya, dan politik.\nManakah yang merupakan contoh bentuk kerja sama antarnegara yang dilakukan Indonesia?",
        img: "",
        options: [
          "Indonesia menutup hubungan perdagangan dengan Amerika Serikat",
          "Indonesia dan Jepang saling membantu dalam bidang pendidikan melalui pertukaran pelajar",
          "Suatu negara hanya mengandalkan sumber daya sendiri tanpa bantuan negara lain",
          "Negara melarang masuknya budaya asing secara keseluruhan",
        ],
        answer: "B",
      },
      {
        q: "Contoh yang termasuk budaya benda adalah ....",
        img: "",
        options: [
          "Upacara adat",
          "Lagu daerah",
          "Rumah adat",
          "Norma masyarakat",
        ],
        answer: "C",
      },
      {
        q: "Yang termasuk contoh budaya tak benda adalah ....",
        img: "",
        options: [
          "Pakaian adat",
          "Lagu daerah",
          "Patung",
          "Senjata tradisional",
        ],
        answer: "B",
      },
      {
        q: "Perhatikan gambar berikut!\nBerdasarkan gambar tersebut, dapat disimpulkan bahwa rotasi Bumi menyebabkan ....",
        img: "IPAS-21.webp",
        options: [
          "perubahan musim di berbagai negara",
          "perbedaan lama siang dan malam",
          "terjadinya siang dan malam",
          "gerak semu tahunan Matahari",
        ],
        answer: "C",
      },
      {
        q: "“Bumi bergerak mengelilingi Matahari dalam waktu sekitar 365¼ hari.”\nPeristiwa tersebut mengakibatkan ....",
        img: "",
        options: [
          "terjadinya siang dan malam",
          "terjadinya gerhana Bulan",
          "pergantian musim",
          "perbedaan waktu di berbagai wilayah",
        ],
        answer: "C",
      },
      {
        q: "Ciri-ciri planet yang tepat berdasarkan pernyataan bahwa planet mengelilingi Matahari dan tidak memiliki cahaya sendiri adalah ....",
        img: "",
        options: [
          "Memiliki cahaya sendiri dan tidak bergerak",
          "Mengelilingi Bumi dan memancarkan cahaya",
          "Mengelilingi Matahari dan tidak memiliki cahaya sendiri",
          "Tidak bergerak dan hanya terlihat pada malam hari",
        ],
        answer: "C",
      },
      {
        q: "Energi yang tidak akan habis adalah energi yang dapat diperbarui dan tersedia secara terus-menerus di alam. Contoh energi yang tidak akan habis adalah ....",
        img: "",
        options: [
          "Energi batu bara",
          "Energi minyak bumi",
          "Energi matahari",
          "Energi gas alam",
        ],
        answer: "C",
      },
      {
        q: "Perhatikan daftar sumber energi di bawah ini!\n1. Batubara\n2. Angin\n3. Minyak bumi\n4. Cahaya matahari\n5. Gas alam\n6. Aliran air sungai\nBerdasarkan pernyataan di atas, yang termasuk contoh sumber energi terbarukan ditunjukkan oleh nomor ....",
        img: "",
        options: ["1, 2, dan 3", "2, 4, dan 6", "1, 3, dan 5", "4, 5, dan 6"],
        answer: "B",
      },
      {
        q: "Tumbuhan hijau dapat membuat makanan sendiri dengan bantuan cahaya matahari. Berdasarkan pernyataan tersebut, makna fotosintesis adalah ....",
        img: "",
        options: [
          "proses penyerapan air oleh akar",
          "proses tumbuhan berkembang biak",
          "proses pembuatan makanan pada tumbuhan dengan bantuan cahaya matahari",
          "proses penguapan air pada daun",
        ],
        answer: "C",
      },
      {
        q: "Pak Budi menanam padi di sawah, kemudian hasil panennya dijual ke pasar oleh pedagang. Kegiatan yang dilakukan pedagang tersebut termasuk ....",
        img: "",
        options: ["produksi", "konsumsi", "distribusi", "investasi"],
        answer: "C",
      },
      {
        q: "Perhatikan pernyataan berikut!\n1. Dapat menarik benda tertentu\n2. Memiliki dua kutub\n3. Semua benda dapat ditarik magnet\nSifat magnet yang benar ditunjukkan oleh nomor ....",
        img: "",
        options: ["1 dan 2", "1 dan 3", "2 dan 3", "1, 2, dan 3"],
        answer: "A",
      },
      {
        q: "Hubungan antara dua tulang yang memungkinkan terjadinya gerakan disebut ....",
        img: "",
        options: ["otot", "rangka", "sendi", "saraf"],
        answer: "C",
      },
      {
        q: "Saat tangan kita menyentuh benda panas, tanpa berpikir tangan langsung menjauh. Bagian sistem saraf yang bekerja pada peristiwa tersebut adalah ....",
        img: "",
        options: ["saraf pusat", "saraf tepi", "saraf refleks", "otot rangka"],
        answer: "C",
      },
      {
        q: "Dalam melawan penjajah Belanda, Tuanku Imam Bonjol menggunakan strategi perang ....",
        img: "",
        options: [
          "perang terbuka",
          "perang gerilya",
          "perang laut",
          "perang dagang",
        ],
        answer: "B",
      },
      {
        q: "Peristiwa proklamasi kemerdekaan Indonesia terjadi pada tanggal ....",
        img: "",
        options: [
          "1 Juni 1945",
          "17 Agustus 1945",
          "28 Oktober 1928",
          "10 November 1945",
        ],
        answer: "B",
      },
      {
        q: "Indonesia terletak di antara dua benua dan dua samudra, yaitu ....",
        img: "",
        options: [
          "Benua Asia dan Australia serta Samudra Hindia dan Pasifik",
          "Benua Asia dan Afrika serta Samudra Atlantik dan Hindia",
          "Benua Eropa dan Australia serta Samudra Pasifik dan Atlantik",
          "Benua Amerika dan Asia serta Samudra Pasifik dan Arktik",
        ],
        answer: "A",
      },
      {
        q: "Organisasi internasional yang beranggotakan negara-negara Asia Tenggara adalah ....",
        img: "",
        options: ["PBB", "ASEAN", "WTO", "OPEC"],
        answer: "B",
      },
      {
        q: "Bulan melakukan revolusi mengelilingi Bumi. Dampak dari revolusi Bulan adalah ....",
        img: "",
        options: [
          "terjadinya siang dan malam",
          "perubahan musim",
          "gerhana Bulan dan fase-fase Bulan",
          "perbedaan waktu di berbagai wilayah",
        ],
        answer: "C",
      },
      {
        q: "Saat es batu dibiarkan di tempat terbuka, lama-kelamaan akan berubah menjadi air. Perubahan wujud tersebut disebut ....",
        img: "",
        options: ["membeku", "mencair", "menguap", "menyublim"],
        answer: "B",
      },
      {
        q: "Perhatikan kegiatan berikut!\n1. Cahaya dapat dipantulkan\n2. Cahaya merambat lurus\n3. Cahaya menembus benda gelap\nSifat cahaya yang benar ditunjukkan oleh nomor ....",
        img: "",
        options: ["1 dan 2", "1 dan 3", "2 dan 3", "1, 2, dan 3"],
        answer: "A",
      },
      {
        q: "Bangsa Eropa datang ke Indonesia karena tertarik mencari kekayaan, menyebarkan agama, dan memperoleh kejayaan. Istilah untuk tujuan tersebut adalah ....",
        img: "",
        options: [
          "Politik Etis",
          "Gold, Gospel, Glory",
          "Devide et Impera",
          "Tanam Paksa",
        ],
        answer: "B",
      },
      {
        q: "Perhatikan pasangan benua dan julukannya berikut!\n1. Asia = Benua Kuning\n2. Afrika = Benua Hitam\n3. Australia = Benua Merah\nPasangan yang benar adalah ....",
        img: "",
        options: ["1 dan 2", "1 dan 3", "2 dan 3", "1, 2, dan 3"],
        answer: "D",
      },
      {
        q: "Urutan planet dalam tata surya yang benar dimulai dari yang terdekat dengan Matahari adalah ....",
        img: "",
        options: [
          "Venus -> Merkurius -> Bumi -> Mars",
          "Merkurius -> Venus -> Bumi -> Mars",
          "Bumi -> Venus -> Merkurius -> Mars",
          "Mars -> Bumi -> Venus -> Merkurius",
        ],
        answer: "B",
      },
      {
        q: "Hubungan antara dua tulang yang tidak dapat digerakkan disebut sendi ....",
        img: "",
        options: ["peluru", "engsel", "mati", "putar"],
        answer: "C",
      },
      {
        q: "Otak berfungsi sebagai pusat pengatur seluruh aktivitas tubuh manusia. Pernyataan tersebut menunjukkan fungsi dari ....",
        img: "",
        options: [
          "sistem pernapasan",
          "sistem pencernaan",
          "sistem saraf",
          "sistem peredaran darah",
        ],
        answer: "C",
      },
      {
        q: "Tulang punggung membungkuk ke belakang sehingga posisi tubuh menjadi bongkok disebut ....",
        img: "",
        options: ["lordosis", "skoliosis", "kifosis", "osteoporosis"],
        answer: "C",
      },
      {
        q: "Urutan bangsa Eropa yang datang ke Indonesia adalah ....",
        img: "",
        options: [
          "Belanda -> Portugis -> Spanyol",
          "Portugis -> Spanyol -> Belanda",
          "Spanyol -> Belanda -> Portugis",
          "Belanda -> Spanyol -> Portugis",
        ],
        answer: "B",
      },
      {
        q: "Makna “gold” dalam semboyan Gold, Gospel, Glory adalah ....",
        img: "",
        options: [
          "menyebarkan agama",
          "mencari kekayaan",
          "mencari kekuasaan",
          "membangun persahabatan",
        ],
        answer: "B",
      },
      {
        q: "Benua yang dijuluki Benua Hitam adalah ....",
        img: "",
        options: ["Asia", "Amerika", "Australia", "Afrika"],
        answer: "D",
      },
      {
        q: "Negara yang berada di Benua Asia adalah ....",
        img: "",
        options: ["Brasil", "Jepang", "Mesir", "Kanada"],
        answer: "B",
      },
      {
        q: "Indonesia menjual hasil laut ke Jepang. Kegiatan menjual barang ke luar negeri disebut ....",
        img: "",
        options: ["impor", "distribusi", "ekspor", "konsumsi"],
        answer: "C",
      },
      {
        q: "Rotasi Bumi menyebabkan ....",
        img: "",
        options: [
          "pergantian musim",
          "gerhana Matahari",
          "terjadinya siang dan malam",
          "perubahan fase Bulan",
        ],
        answer: "C",
      },
      {
        q: "Revolusi Bumi mengakibatkan ....",
        img: "",
        options: [
          "terjadinya siang dan malam",
          "perubahan musim",
          "pasang surut air laut",
          "gerak semu harian Matahari",
        ],
        answer: "B",
      },
    ],
  },
  {
    id: "SENI",
    title: "SBDP",
    classDefault: "Kelas 6 (Aqaba)",
    duration: 90,
    theme: "from-yellow-500 to-orange-500",
    secure: "7717",
    questions: [
      {
        q: "Gambar tersebut menunjukkan alat musik Drum.\nSumber bunyi alat musik tersebut berasal dari …",
        options: [
          "Getaran udara",
          "Getaran membran akibat pukulan",
          "Gesekan senar",
          "Tiupan logam",
        ],
        answer: "B",
        img: "SENI-1.webp",
      },
      {
        q: "Manakah di bawah ini yang termasuk alat musik melodis?",
        options: ["Drum", "Tamborin", "Seruling", "Gong"],
        answer: "C",
        img: "",
      },
      {
        q: "Berdasarkan tabel di atas, jenis suara pria dengan nada paling tinggi adalah …",
        options: ["bass", "bariton", "tenor", "alto"],
        answer: "C",
        img: "SENI-3.webp",
      },
      {
        q: "Perhatikan ciri-ciri berikut:\n- Terbuat dari bilah-bilah kayu\n- Menghasilkan nada yang beragam\n- Dimainkan dengan alat pemukul\nAlat musik dari Sulawesi Utara yang sesuai dengan ciri-ciri tersebut adalah …",
        options: ["Kolintang", "Tifa", "Kendang", "Seruling"],
        answer: "A",
        img: "",
      },
      {
        q: "Yang dimaksud dengan artikulasi dalam menyanyi adalah ..",
        options: [
          "Kecepatan nada",
          "Kejelasan pengucapan kata",
          "Tinggi rendah nada",
          "Keras lembut suara",
        ],
        answer: "B",
        img: "",
      },
      {
        q: "Latihan intonasi yang baik untuk menghindari nada fals adalah …",
        options: [
          "Berteriak dengan suara keras",
          "mendengarkan musik rock",
          "menyanyikan tangga nada secara berulang",
          "Menirukan suara hewan",
        ],
        answer: "A",
        img: "",
      },
      {
        q: "Nilai not gambar di atas adalah …",
        options: ["1 ketuk", "2 ketuk", "3 ketuk", "4 ketuk"],
        answer: "B",
        img: "SENI-7.webp",
      },
      {
        q: "Ketepatan tinggi rendahnya nada yang dihasilkan oleh seorang penyanyi atau alat musik disebut …",
        options: ["Intonasi", "Notasi", "Irama", "Nada"],
        answer: "C",
        img: "",
      },
      {
        q: "Mulut terbuka kecil, bibir agak ditarik ke samping, dan lidah berada di bagian depan.\nPosisi mulut tersebut digunakan untuk mengucapkan huruf vokal ....",
        options: ["A", "I", "U", "O"],
        answer: "B",
        img: "SENI-9.webp",
      },
      {
        q: "Perhatikan judul lagu wajib nasional berikut!\nIndonesia Raya\nIbu Kita Kartini\nBagimu Negeri\nMaju Tak Gentar\nLagu yang dinyanyikan dengan gaya legato (halus dan mengalir) adalah ....",
        options: [
          "Indonesia Raya",
          "Ibu Kita Kartini",
          "Bagimu Negeri",
          "Maju Tak Gentar",
        ],
        answer: "C",
        img: "",
      },
      {
        q: "Contoh alat musik melodis yang sering digunakan disekolah adalah ..",
        options: ["Simbal", "Tamborin", "Pianika", "Gendang"],
        answer: "C",
        img: "",
      },
      {
        q: "Manakah dibawah ini yang merupakan contooh alat musik ritmis ..",
        options: ["Gitar", "pianika", "drum", "rekorder"],
        answer: "C",
        img: "",
      },
      {
        q: "Dalam kegiatan bernyanyi, kita mengenal istilah phrasering. Apa yang dimaksud dengan phrasering?",
        options: [
          "kejelasan dalam pengucapan kata-kata saat bernyanyi",
          "cepat lambatnya lagu dinyanyikan",
          "teknik pemenggalan kalimat lagu baik dan benar sehingga mudah di mengerti",
          "ketepatan dinggi rendahnya nada yang dibunyikan oleh penyanyi",
        ],
        answer: "C",
        img: "",
      },
      {
        q: "Lagu daerah yang berjudul 'Manuk Dadali' memiliki makna tentang kegagahan burung garuda. Lagu ini berasal dari daerah…",
        options: ["Jawa barat", "jawa timur", "Jawa Tengah", "banten"],
        answer: "A",
        img: "",
      },
      {
        q: "hidup takan mungkin\ntanpa perjuangan\ntanpa pengorbanan\nmulia adanya\nberpegangan tangan\ndalam satu cita\ndemi masa depan\nindonesia …..\n\njudul lagu yang tepat pada lirik lagu di atas adalah…",
        options: [
          "Indonesia raya",
          "Indonesia merdeka",
          "Indonesia jaya",
          "Indonesia mulia",
        ],
        answer: "C",
        img: "",
      },
      {
        q: "dibawah ini merupakan alat musik perkusi, kecuali ….",
        options: ["Gamelan", "Kecapi", "Gendang", "Arumba"],
        answer: "B",
        img: "",
      },
      {
        q: 'Perhatikan pernyataan berikut!\n"Dalam dunia musik, terdapat sebuah sistem simbol atau lambang yang digunakan untuk menuliskan nada-nada agar dapat dibaca, dipelajari, dan dimainkan kembali oleh pemusik dengan nada dan ritme yang tepat sesuai keinginan penciptanya."\nBerdasarkan pernyataan di atas, sistem simbol yang dimaksud adalah…',
        options: [
          "Partitur, yaitu naskah lengkap yang berisi seluruh instrumen dalam sebuah pementasan musik.",
          "Melodi, yaitu rangkaian nada-nada yang disusun secara ritmis dengan urutan yang teratur.",
          "Notasi musik, yaitu sistem penulisan karya musik melalui simbol angka atau gambar pada garis paranada.",
          "Aransemen, yaitu upaya menggubah kembali sebuah karya musik agar tampil lebih bervariasi.",
        ],
        answer: "C",
        img: "",
      },
      {
        q: "Perhatikan pernyataan-pernyataan di bawah ini!\n1) Menggunakan simbol angka 1 sampai 7 untuk mewakili nada do sampai si.\n2) Menggunakan garis paranada (lima garis mendatar) untuk meletakkan simbol nada.\n3) Tanda diam dilambangkan dengan angka 0.\n4) Tinggi rendah nada ditentukan oleh bentuk dan letak bulatan pada garis atau spasi.\n5) Titik di atas angka menunjukkan nada tinggi.\nBerdasarkan pernyataan tersebut, ciri-ciri yang secara khusus menunjukkan Notasi Angka ditunjukkan oleh nomor…",
        options: ["1, 2, dan 4", "1, 3, dan 5", "2, 3, dan 4", "3, 4, dan 5"],
        answer: "B",
        img: "",
      },
      {
        q: "Jumlah ruang kosong atau spasi yang terdapat pada baris paranada adalah …",
        options: ["Tiga spasi", "empat spasi", "lima spasi", "enam spasi"],
        answer: "B",
        img: "",
      },
      {
        q: "Istilah lain yang sering dignakan untuk menyebut ritme adalah …",
        options: ["Nada", "melodi", "ketukan", "irama"],
        answer: "C",
        img: "",
      },
      {
        q: "Dalam musik, terdapat istilah seperti allegro, andante, dan forte yang digunakan untuk menunjukkan tempo dan dinamika lagu.\nIstilah-istilah dalam musik tersebut berasal dari bahasa ….",
        options: ["Inggris", "Jerman", "Italia", "Prancis"],
        answer: "C",
        img: "",
      },
      {
        q: "Dalam sebuah lagu terdapat tanda allegro yang menunjukkan tempo cepat dan tanda forte yang menunjukkan bunyi dimainkan dengan keras.\nManakah pasangan yang tepat antara tanda tempo dan dinamika berdasarkan pernyataan tersebut?",
        options: [
          "Allegro = keras, Forte = cepat",
          "Allegro = cepat, Forte = keras",
          "Allegro = lambat, Forte = lembut",
          "Allegro = lembut, Forte = lambat",
        ],
        answer: "B",
        img: "",
      },
      {
        q: "Perhatikan pernyataan berikut:\nAlat musik modern adalah alat musik yang berkembang di zaman sekarang dan biasanya menggunakan teknologi atau bahan yang lebih maju.\nBerdasarkan pernyataan tersebut, yang termasuk contoh alat musik modern adalah ....",
        options: ["Angklung", "Gamelan", "Gitar listrik", "Kendang"],
        answer: "C",
        img: "",
      },
      {
        q: "Perhatikan pernyataan berikut:\nAlat musik tradisional merupakan alat musik yang berkembang secara turun-temurun dan menjadi bagian dari budaya suatu daerah.\nBerdasarkan pernyataan tersebut, arti alat musik tradisional adalah ....",
        options: [
          "Alat musik yang hanya dimainkan di luar negeri",
          "Alat musik modern yang menggunakan teknologi canggih",
          "Alat musik yang berasal dari budaya daerah dan diwariskan secara turun-temurun",
          "Alat musik yang hanya digunakan untuk hiburan pribadi",
        ],
        answer: "C",
        img: "",
      },
      {
        q: "Perhatikan daftar alat musik di bawah ini!\n1. Sasando\n2. Angklung\n3. Kolintang\n4. Tifa\nAlat musik yang berasal dari daerah Jawa Barat dan dimainkan dengan cara digoyangkan ditunjukkan oleh nomor ....",
        options: ["1", "2", "3", "4"],
        answer: "B",
        img: "",
      },
      {
        q: "Perhatikan not angka berikut!\n1 - 2 - 3 - 5 - 6\nUrutan nada tersebut jika dibaca adalah ....",
        options: [
          "do-re-mi-sol-la",
          "do-re-fa-sol-la",
          "re-mi-fa-la-si",
          "do-re-fa-sol-la",
        ],
        answer: "A",
        img: "",
      },
      {
        q: "Dalam sebuah pertunjukan lagu, penyanyi menyanyikan lagu dengan suara keras pada bagian semangat dan suara lembut pada bagian sedih. Hal tersebut disebut ....",
        options: ["tempo", "artikulasi", "dinamika", "notasi"],
        answer: "C",
        img: "",
      },
      {
        q: "Not balok yang berwarna hitam penuh dan memiliki tangkai disebut ....",
        options: [
          "not penuh",
          "not setengah",
          "not seperempat",
          "not seperdelapan",
        ],
        answer: "C",
        img: "SENI-28.webp",
      },
      {
        q: "Saat bernyanyi, Rina menggunakan napas dari bagian diafragma agar suara lebih panjang dan stabil. Teknik pernapasan yang digunakan adalah ....",
        options: [
          "pernapasan dada",
          "pernapasan perut",
          "pernapasan diafragma",
          "pernapasan pendek",
        ],
        answer: "C",
        img: "",
      },
      {
        q: "Pengucapan kata dalam lagu harus jelas agar pesan lagu dapat dipahami pendengar. Dalam seni musik hal tersebut disebut ....",
        options: ["tempo", "artikulasi", "intonasi", "dinamika"],
        answer: "B",
        img: "",
      },
      {
        q: "Tanda ekspresi lagu yang digunakan untuk menyanyikan lagu dengan lembut adalah ....",
        options: ["forte", "allegro", "piano", "presto"],
        answer: "C",
        img: "",
      },
      {
        q: "Lagu “Maju Tak Gentar” biasanya dinyanyikan dengan ekspresi ....",
        options: ["sedih", "semangat dan gagah", "lembut", "bingung"],
        answer: "B",
        img: "",
      },
      {
        q: "Daerah Jawa Barat memiliki lagu daerah yang terkenal yaitu ....",
        options: [
          "Ampar-Ampar Pisang",
          "Bungong Jeumpa",
          "Manuk Dadali",
          "Yamko Rambe Yamko",
        ],
        answer: "C",
        img: "",
      },
      {
        q: "Lagu modern biasanya dipengaruhi oleh perkembangan ....",
        options: [
          "adat lama saja",
          "permainan tradisional",
          "teknologi dan zaman",
          "cerita rakyat",
        ],
        answer: "C",
        img: "",
      },
      {
        q: "Dalam sebuah grup musik, gitar digunakan untuk mengiringi keselarasan nada lagu. Fungsi gitar dalam keadaan tersebut adalah ....",
        options: ["melodi", "ritmis", "harmoni", "tempo"],
        answer: "C",
        img: "",
      },
      {
        q: "Tiga alat musik yang termasuk alat musik ritmis adalah ....",
        options: [
          "pianika, suling, gitar",
          "tamborin, drum, triangle",
          "recorder, piano, biola",
          "kecapi, suling, angklung",
        ],
        answer: "B",
        img: "SENI-36.webp",
      },
      {
        q: "Suara wanita yang tinggi dan lembut dalam paduan suara disebut ....",
        options: ["tenor", "bass", "alto", "sopran"],
        answer: "D",
        img: "",
      },
      {
        q: "Sikap yang baik saat bernyanyi di depan kelas adalah ....",
        options: [
          "menunduk dan diam",
          "berdiri tegak dan percaya diri",
          "berbicara sendiri saat bernyanyi",
          "terus melihat ke bawah",
        ],
        answer: "B",
        img: "",
      },
      {
        q: "Di bawah ini yang termasuk judul lagu modern adalah ....",
        options: ["Hujan", "Halo-Halo Bandung", "Bubuy Bulan", "Tokecang"],
        answer: "A",
        img: "",
      },
      {
        q: "Posisi mulut untuk mengucapkan huruf vokal “i” adalah ....",
        options: [
          "terbuka bulat lebar",
          "terbuka menyamping sempit",
          "bibir dirapatkan",
          "mulut tertutup",
        ],
        answer: "B",
        img: "SENI-40.webp",
      },
      {
        q: "Ragam hias adalah ....",
        options: [
          "gambar bebas tanpa pola",
          "hiasan untuk memperindah suatu benda",
          "tulisan untuk poster",
          "gambar bangunan modern",
        ],
        answer: "B",
        img: "",
      },
      {
        q: "Motif di atas termasuk ragam hias ....",
        options: ["fauna", "geometris", "flora", "figuratif"],
        answer: "C",
        img: "SENI-42.webp",
      },
      {
        q: "Motif tersebut termasuk ragam hias ....",
        options: ["flora", "fauna", "geometris", "abstrak"],
        answer: "B",
        img: "SENI-43.webp",
      },
      {
        q: "Urutan langkah yang benar dalam membuat gambar ragam hias adalah ....",
        options: [
          "mewarnai - membuat pola - menghapus",
          "membuat pola - menggambar - mewarnai",
          "mewarnai - memotong - menggambar",
          "memotong - menggambar - menyalin",
        ],
        answer: "B",
        img: "",
      },
      {
        q: "Alat yang paling utama digunakan untuk membuat sketsa ragam hias adalah ....",
        options: ["penggaris", "pensil", "cat minyak", "lem"],
        answer: "B",
        img: "SENI-45.webp",
      },
      {
        q: "Benda berikut yang dapat dijadikan karya seni dari limbah rumah tangga adalah ....",
        options: ["botol plastik bekas", "emas", "beras baru", "air mineral"],
        answer: "A",
        img: "",
      },
      {
        q: "Sebelum membuat vas bunga dari botol plastik bekas, langkah awal yang harus dilakukan adalah ....",
        options: [
          "langsung diberi warna",
          "dijual kembali",
          "dibersihkan terlebih dahulu",
          "dipotong sembarangan",
        ],
        answer: "C",
        img: "",
      },
      {
        q: "Mendaur ulang limbah menjadi karya seni memiliki manfaat untuk ....",
        options: [
          "menambah sampah",
          "merusak lingkungan",
          "menjaga kebersihan lingkungan dan meningkatkan kreativitas",
          "membuang barang lebih banyak",
        ],
        answer: "C",
        img: "",
      },
      {
        q: "Karya seni di atas dibuat dari limbah ....",
        options: ["kayu", "kaca", "logam", "kertas"],
        answer: "D",
        img: "SENI-49.webp",
      },
      {
        q: "Dalam konsep 3R, kata “Recycle” berarti ....",
        options: [
          "mengurangi penggunaan barang",
          "menggunakan kembali barang yang masih layak",
          "mengolah kembali barang bekas menjadi barang baru",
          "membeli barang baru",
        ],
        answer: "C",
        img: "",
      },
    ],
  },
  {
    id: "BSUN",
    title: "Bahasa Sunda",
    classDefault: "Kelas 6 (Aqaba)",
    duration: 90,
    theme: "from-purple-500 to-red-500",
    secure: "7183",
    questions: [
      {
        q: "Kalimah pananya anu merenah pikeun nanyakeun jalma / tokoh nyaeta ………",
        options: [
          "Dimana Raden Dewi Sartika ngadirikeun sakola?",
          "Saha anu gaduh cita-cita sangkan wanoja sunda henteu bodo jeung bisa mandiri?",
          "Naon wae anu di ajarkeun di sakola istri?",
          "Iraha Raden Dewi Sartika ditetepkeun janten Pahlawan Nasional ?",
        ],
        answer: "B",
        img: "",
      },
      {
        q: "Kecap rajekan dwireka anu aya dina teks di luhur nyaeta….",
        options: ["ti leuleutik", "cita-cita", "rupa-rupi", "sakola-sakola"],
        answer: "C",
        img: "",
      },
      {
        q: "Perhatikeun sajak di handap!\nindung\nanjeun cahaya hirup abdi\nsalawasna nyaangan jalan\ndi peuting jeung di beurang\nmugia gusti maparin kasehatan\nPamakéan aksara gedé dina kalimah nu bener tina sajak di luhur nyaéta...",
        options: [
          "Nulis kecap indung jadi Indung",
          "Nulis kecap gusti jadi Gusti",
          "Nulis kecap indung jadi Indung jeung gusti jadi Gusti",
          "Sadaya kecap dina awal padalisan kudu make aksara gedé",
        ],
        answer: "C",
        img: "",
      },
      {
        q: "Perhatikeun sajak di handap!\nangin ngahiliwir lalaunan\ndaun murag tina tangkal\nsora manuk ngahiuk di leuweung\nhaté karasa tengtrem\nningali alam anu éndah\n\nJudul sajak anu paling merenah nyaéta...",
        options: [
          "Kahirupan Kota",
          "Kaéndahan Alam",
          "Kagiatan Sakola",
          "Kaulinan Barudak",
        ],
        answer: "B",
        img: "",
      },
      {
        q: "Baca sempalan kawih di handap ieu !\nCita-cita \nCipt. Ubun R Kubarsah\n…\nCita-cita, cita-cita\nMangka laksana mun diajarna rajin\nCita-cita, cita-cita\nPareng laksana mun diajarna tigin\n…\nParibasa anu merenah supaya cita-cita urang kahontal nyaeta …",
        options: [
          "Adat kakurung ku iga",
          "Cikaracak ninggang batu, laun-laun jadi legok",
          "Haripeut ku teuteureuyan",
          "Kandel kulit beungeut",
        ],
        answer: "B",
        img: "",
      },
      {
        q: "Amir : “ Sep, ari bapa digawena naon ?”\nAsep : “ Bapa mah sok ahli dina ngalakonkeun wayang.”\nIstilah kecap pagawean pikeun jalma anu ahli dina ngalakonkeun wayang disebut …",
        options: ["Dalang", "Paraji", "Kusir", "Sinden"],
        answer: "A",
        img: "",
      },
      {
        q: "Perhatikeun kalimah di handap ieu!\n“Ibu bade angkat ka pasar.”\nKalimah di luhur kaasup kana ragam basa ....",
        options: ["Basa loma", "Basa kasar", "Basa hormat", "Basa gaul"],
        answer: "C",
        img: "",
      },
      {
        q: "Perhatikeun kalimah di handap ieu!\n“Abdi badé tuang heula sateuacan angkat.”\nKalimah di luhur kaasup kana ragam basa ....",
        options: [
          "Basa loma",
          "Basa formal (hormat/lemes)",
          "Basa kasar",
          "Basa gaul",
        ],
        answer: "B",
        img: "",
      },
      {
        q: "Nu kaasup kanaa carpon nyaeta ..",
        options: ["Lingkungan", "Tema", "Tahun", "Watek"],
        answer: "B",
        img: "",
      },
      {
        q: "Bulan harep Agus rek meli sapedah, nungguan bapa gajihan.\nKecap gajih dina kalimah eta ngandung harti ..",
        options: ["Panghasilan", "Kadaharan", "Karesep", "Daging"],
        answer: "A",
        img: "",
      },
      {
        q: "Kecap 'internét' dina téks di luhur mangrupakeun conto kecap serepan. Naon hartina kecap serepan téh?",
        options: [
          "kecap nu hartina sarua jeung kecap sejen",
          "kecap anu dicokot tina basa asing atawa basa sejen",
          "kecep asalna tina basa sorangan",
          "kecap anu boga harti sabalikna",
        ],
        answer: "B",
        img: "",
      },
      {
        q: 'Musibah di Lembur Pasir Lembur Pasir anu biasana tiiseun, poé ieu mah jadi ramé. Hujan gedé ti peuting kénéh can raat-raat. Di sisi jalan, Mang Udin keur sedih ningali sawahna anu kakeueum ku caah. "Rék kumaha nasib panén kuring ayeuna?" gerentesna dina jero haté. Sanajan kitu, tatangga-tatangga Mang Udin saperti Pa RT jeung Kang Dadang buru-buru datang mantuan ngévakuasi barang-barang Mang Udin ka tempat anu leuwih aman. Maranéhna babarengan silih tulungan sangkan musibah ieu teu nambahan korban.\nSaha palaku utama dina cutatan carpon di luhur?',
        options: ["Pak RT", "Masyarakat", "kang dadang", "mang udin"],
        answer: "D",
        img: "",
      },
      {
        q: "nita geus tilu poe teu lebet sakola\nsaurna mamahna nuju udur.\n\nsinonim kecap udur nyaeta",
        options: ["Hajat", "Geuring", "Liburan", "Jangar"],
        answer: "B",
        img: "",
      },
      {
        q: "kunaon aya banjir\nbaheula leweung tara diganggu\ncai hujan nu turun ……………………..\nayeuna leweung mindeng diganggu\ncai hujan turun ngagepapan ka leweung\n\neusi kalimat kosong nu tepat nyaeta….",
        options: [
          "ditangkeup leweung",
          "ditangkeup gunung",
          "disiuk leuweung",
          "disiuk gunung",
        ],
        answer: "A",
        img: "",
      },
      {
        q: 'Pék baca cutatan téks di handap ieu!\n"Dina jaman globalisasi ayeuna, alat komunikasi saperti telepon sélulér geus jadi kabutuhan poko masarakat. Lian ti éta, akses internét anu beuki gancang mawa parobahan gedé dina widang teknologi sarta informasi. Hal ieu ngabalukarkeun kabudayaan asing gampang asup ka nagara urang."\nKecap anu kaasup kana kecap serapan (tina basa asing/Indonésia) anu aya dina éta téks nyaéta…',
        options: [
          "Jaman, globalisasi, masarakat",
          "Telepon, akses, teknologi",
          "Alat, kabutuhan, parobahan",
          "Gedé, widang, gancang",
        ],
        answer: "B",
        img: "",
      },
      {
        q: "Pék titénan tabél cutatan carpon di handap ieu!\nDumasar kana tabél di luhur, cutatan anu ngagambarkeun eusi carita pondok ngeunaan musibah alam banjir ditémbongkeun ku nomer…",
        options: [
          "1, 2, jeung 3",
          "1, 3, jeung 5",
          "2, 3, jeung 4",
          "3, 4, jeung 5",
        ],
        answer: "B",
        img: "BSUN-16.webp",
      },
      {
        q: "Dina hiji peuting, hujan turun kacida gedéna nepi ka walungan di lembur jadi ngalobaan cai. Isukna, kajadian banjir nu ngageleger ka sababaraha imah warga. Di sisi séjén, di lembur tatangga aya urug taneuh sabab taneuhna laleuleus ku hujan. Sababaraha warga ogé ngarasa sieun ku kajadian lini leutik nu karasa peuting éta. Sanajan kitu, warga silih tulungan pikeun ngungkulan musibah anu kajadian.\nNaon harti utama tina carita pondok di luhur?",
        options: [
          "Warga bungah sabab loba cai di walungan",
          "Kajadian rupa-rupa musibah alam jeung pentingna silih tulungan",
          "Warga keur ulin di lembur tatangga",
          "Hujan ngan saukur kajadian biasa di peuting",
        ],
        answer: "B",
        img: "",
      },
      {
        q: "Globalisasi nyaéta hiji kaayaan dimana dunya karasa beuki deukeut lantaran kamajuan téknologi jeung komunikasi. Ayeuna, urang bisa gampang meunang informasi ti nagara séjén ngaliwatan internét, televisi, atawa telepon pinter. Globalisasi ogé ngajadikeun budaya ti luar nagara bisa asup jeung dipikawanoh ku masarakat urang. \nNaon harti globalisasi dumasar kana téks di luhur?",
        options: [
          "Kaayaan dimana hiji nagara hirup mandiri tanpa hubungan jeung nagara séjén",
          "Kaayaan dunya anu beuki jauh jeung hésé komunikasi",
          "Kaayaan dunya anu beuki deukeut lantaran kamajuan téknologi jeung komunikasi",
          "Kaayaan dimana budaya luar teu bisa asup ka hiji nagara",
        ],
        answer: "C",
        img: "",
      },
      {
        q: "Kecap bawa ditambah rarangken di- jadi …",
        options: ["di bawa", "dibawa", "di bawakeun", "dibawaan"],
        answer: "B",
        img: "",
      },
      {
        q: "Perhatikeun téks déskripsi di handap ieu!\nDi jaman kiwari, loba siswa ngagunakeun laptop jeung internét pikeun néangan bahan pelajaran. Ku ayana téknologi, komunikasi jeung diajar jadi leuwih gampang jeung gancang.\nIstilah téknologi anu aya dina téks di luhur nyaéta ....",
        options: ["siswa", "pelajaran", "laptop jeung internét", "komunikasi"],
        answer: "C",
        img: "",
      },
      {
        q: "Téks déskripsi anu paling merenah ngeunaan globalisasi nyaéta ....",
        options: [
          "Kiwari jalma-jalma bisa komunikasi jeung néangan informasi kalayan gancang maké internét jeung telepon pinter.",
          "Patani keur melak paré di sawah bari maké pacul tradisional.",
          "Barudak keur ulin kaulinan oray-orayan di lapang.",
          "Ibu keur masak sangu liwet di dapur imah.",
        ],
        answer: "A",
        img: "",
      },
      {
        q: "Teks Biografi sok disebut oge ..",
        options: [
          "Teks anu ngenaan riwayat hirup",
          "Teks ngenaan sabab akibat",
          "Teks anu ngadeskripsikeun",
          "Teks anu nyaritakeun hal anu aya",
        ],
        answer: "A",
        img: "",
      },
      {
        q: "Perhatikeun téks wawancara di handap ieu:\nPawawancara: “Naon anu anjeun lakukeun dina ngajalankeun usaha ieu?”\nNarasumber: “Abdi ngamimitian usaha ti leutik, ngatur sorangan, wani nyanghareupan résiko, sarta terus nyieun inovasi sangkan usaha maju.”\nDumasar kana téks wawancara éta, naon hartina wirausaha téh?",
        options: [
          "Jalba anu digawé ka batur jeung meunang gajih",
          "Jalma anu teu boga pagawean",
          "Jalma anu ngajalankeun usaha sorangan kalayan wani nyanghareupan résiko",
          "Jalma anu ngan ukur ngajual barang batur",
        ],
        answer: "C",
        img: "",
      },
      {
        q: "Perhatikeun pernyataan di handap ieu:\nKecap babasan nyaéta ungkara dina basa Sunda anu miboga harti kias (lain harti sabenerna) jeung dipaké pikeun ngageulisan basa.\nDumasar kana pernyataan éta, nu kaasup kecap babasan nyaéta ....",
        options: [
          "Dahar sangu di imah",
          "Leumpang ka sakola",
          "Leungeun panjang",
          "Maca buku di kelas",
        ],
        answer: "C",
        img: "",
      },
      {
        q: "Saméméh wawancara, hal anu kudu dipersiapkeun nyaéta ....",
        options: ["kaulinan", "daptar patanyaan", "kadaharan", "baju olahraga"],
        answer: "B",
        img: "",
      },
      {
        q: "Robah kalimah aktif di handap jadi kalimah pasif!\n“Ibu masak sangu di dapur.”",
        options: [
          "Sangu dimasak ku ibu di dapur.",
          "Ibu keur masak sangu.",
          "Dapur keur dipaké masak.",
          "Sangu téh ngeunah pisan.",
        ],
        answer: "A",
        img: "",
      },
      {
        q: "Perhatikeun penggalan pidato di handap!\n“Hayu urang ngajaga kabersihan lingkungan supaya hirup séhat.”\nEusi pidato di luhur nyaéta ....",
        options: [
          "ajakan ngajaga kabersihan",
          "larangan ulin",
          "carita liburan",
          "biografi pahlawan",
        ],
        answer: "A",
        img: "",
      },
      {
        q: "Antonim tina kecap “bersih” nyaéta ....",
        options: ["rapih", "kotor", "hérang", "éndah"],
        answer: "B",
        img: "",
      },
      {
        q: "Perhatikeun kalimah di handap!\n“Naon sababna pahlawan kudu dihargaan?”\nKalimah di luhur kaasup kalimah ....",
        options: ["panyeluk", "parentah", "pananya", "wawaran"],
        answer: "C",
        img: "",
      },
      {
        q: "Kadaharan tradisional khas Tasikmalaya nyaéta ....",
        options: ["gudeg", "empek-empek", "tutug oncom", "rendang"],
        answer: "C",
        img: "",
      },
      {
        q: "Eusian kalimah rumpang di handap!\nDokter jeung perawat kaasup tanaga ....",
        options: ["olahraga", "kaséhatan", "kasenian", "pertanian"],
        answer: "B",
        img: "",
      },
      {
        q: "Kecap barang dina kalimah “Adi meuli sapatu anyar” nyaéta ....",
        options: ["Adi", "meuli", "sapatu", "anyar"],
        answer: "C",
        img: "",
      },
      {
        q: "Perhatikeun paribasa di handap!\n“Cikaracak ninggang batu, laun-laun jadi legok.”\nHartina paribasa di luhur nyaéta ....",
        options: [
          "jalma kudu sombong",
          "usaha terus-terusan bakal ngahasilkeun kasuksesan",
          "hirup kudu boros",
          "ulah daék diajar",
        ],
        answer: "B",
        img: "",
      },
      {
        q: "Babasan “tiis ceuli hérang mata” hartina ....",
        options: ["sedih", "ambek", "bungah", "sieun"],
        answer: "C",
        img: "",
      },
      {
        q: "Eusian kalimah rumpang di handap!\nSupaya awak séhat, urang kudu rutin ....",
        options: ["begadang", "olahraga", "males", "jajan sembarangan"],
        answer: "B",
        img: "",
      },
      {
        q: "Dina kalimah “Bandung téh kota anu éndah”, aksara gede dipaké dina kecap ....",
        options: ["téh", "kota", "Bandung", "éndah"],
        answer: "C",
        img: "",
      },
      {
        q: "Léngkah anu bener pikeun nyaritakeun deui carpon nyaéta ....",
        options: [
          "maca, ngapalkeun, nyimpulkeun",
          "maca, ngartos eusi, nyaritakeun deui ku basa sorangan",
          "ngadangukeun musik, maca, sare",
          "nulis judul hungkul",
        ],
        answer: "B",
        img: "",
      },
      {
        q: "Biografi nyaéta ....",
        options: [
          "teks ngeunaan riwayat hirup hiji jalma",
          "carita pondok lucu",
          "teks pidato resmi",
          "sajak ngeunaan alam",
        ],
        answer: "A",
        img: "",
      },
      {
        q: "Conto kecap barang nyaéta ....",
        options: ["lumpat", "méja", "geulis", "dahar"],
        answer: "B",
        img: "",
      },
      {
        q: "Bagian bubuka dina biantara biasana eusina ....",
        options: [
          "salam bubuka jeung pangbagéa",
          "inti masalah hungkul",
          "kacindekan hungkul",
          "dongéng lucu",
        ],
        answer: "A",
        img: "",
      },
      {
        q: "Perhatikeun kecap di handap!\n“Lauk-pauk”\nKecap di luhur kaasup kecap rajekan ....",
        options: ["dwimurni", "dwireka", "dwilingga", "trilingga"],
        answer: "C",
        img: "",
      },
      {
        q: "Perhatikeun kecap rajekan di handap!\n“Bulak-balik”\nHartina kecap di luhur nyaéta ....",
        options: [
          "cicing waé",
          "maju terus",
          "bolak-balik sababaraha kali",
          "lumpat tarik",
        ],
        answer: "C",
        img: "",
      },
      {
        q: "Robah kalimah aktif di handap jadi pasif!\n“Budi maca buku di perpustakaan.”",
        options: [
          "Buku dibaca ku Budi di perpustakaan.",
          "Budi keur maca buku.",
          "Perpustakaan loba buku.",
          "Buku téh alus.",
        ],
        answer: "A",
        img: "",
      },
      {
        q: "Dina paguneman jeung guru, ragam basa anu merenah nyaéta ....",
        options: ["kasar", "hormat", "loma pisan", "kaulinan"],
        answer: "B",
        img: "",
      },
      {
        q: "Kalimah “Udara di kota jadi panas kusabab polusi” kaasup ....",
        options: [
          "kalimah parentah",
          "kalimah kaayaan",
          "kalimah pananya",
          "kalimah panyeluk",
        ],
        answer: "B",
        img: "",
      },
      {
        q: "Sinonim tina kecap “pinter” nyaéta ....",
        options: ["bodo", "males", "calakan", "sedih"],
        answer: "C",
        img: "",
      },
      {
        q: "Istilah kaséhatan anu dipaké pikeun mariksa suhu awak nyaéta ....",
        options: ["termométer", "obeng", "pacul", "golok"],
        answer: "A",
        img: "",
      },
      {
        q: "Eusian kalimah rumpang di handap!\nUrang kudu nginum cai anu cukup supaya awak tetep ....",
        options: ["gering", "séhat", "males", "kotor"],
        answer: "B",
        img: "",
      },
      {
        q: "Istilah kaséhatan anu patali jeung kabersihan huntu nyaéta ....",
        options: ["sikat huntu", "sapatu", "payung", "papan tulis"],
        answer: "A",
        img: "",
      },
      {
        q: "Perhatikeun penggalan pidato di handap!\n“Barudak sadaya, ulah miceun runtah ka walungan sabab bisa nyababkeun banjir.”\nPesen utama pidato di luhur nyaéta ....",
        options: [
          "ngajak olahraga",
          "ngajaga lingkungan ku henteu miceun runtah sembarangan",
          "ngajak diajar kelompok",
          "ngajak ulin ka walungan",
        ],
        answer: "B",
        img: "",
      },
    ],
  },
];

export default QUIZ_DATA;
